---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  chart: sealed-secrets
  targetNamespace: kube-system
  repo: https://kubernetes-charts.storage.googleapis.com/
  version: 1.10.3