apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAnjJd3XuJ6fz0gm9N+NNbqjPIbTrqnewNxopA9/UVDfoWPcOf12hITFibsRbo+VeOAvfbo2Tl4UgqwHz4GIqX34mtKhOGC8t9CgJhILM1cRxPqki8VX7Jvb5NEfQz/8S/HgIG60xtEv2Y2O677ziHerxUxdSjfUCV2onmt9GKS76afIhrTtDOOOT96lU8dvHdKvVZHy0YZCSCxZUp2KMxg/AGZ3IbWh8n30IYJa5b7BkIFqUhwLOVnaf+50j+YkTtPdU7G8mhxEnFhuOwmK6TSWKXy8DdJbmc21osNtwwDWg2FXV8ADsHeU/hTrwcbvknEdLU+ip49C3JktB1VSxC+K3yZf9aI+l+RmGsQvGRjSdpTKkAZn3rrOewwcx+H1K+ZownTkQoBqyKabZOQArIO8+B4wFuIHhIP3J3B13r2CxcS4dlpejmPryGVFKUDBkoigWVYLnEX2UU5P5AD0bsyeIh40Dn7mnBeQg3YL69rRt7v1ZGIAGsjsCOpMXGOMG8Xu0egeq3QaO96x8ptkh8YYaQd5xqW07OG0/rAgn/xgaeJvFj/jmVoGvT+U4QhYVFmJYu2+w1b+8G9fi5Diam4uPa4WiR+aOUJ0jeZGi3ISZAzicsqQCRZJq0g0V3SBX9RMLIDZCfgIvnytm1UsX31S7HX6TFLbRkNteD4Pqk+oTvCjvH11oWHvQ94HkzEuWMkft4AjgRMMlxbOW6b+L42fhx2cSHrIDH1PX0o+vYpr3zz6DWUF6WnauveWp4QffED7W48RWc7iMWgujfGrMeiamppR5atx5Bp0Sc9wCV6HPfExXKgrWYjRcn34TNvU1qEOEx7FZ7URJQH6dN+/OrxwPX28k57IPg7tGKU6bl/LD7DRN/7KQTlZLrMZkLpJw4ZEiaI452utHbfr8h36TyvLLPBaNWCl60rHSCML4rRWfIp5DpDNkWR
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-helm-values
      namespace: default

