---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0.
    todo: "migrate to common chart"
spec:
  releaseName: hass
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 4.0.0
  values:
    extraEnv:
      TZ: "Europe/Vienna"
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "local-path"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    hostNetwork: true
    vscode:
      enabled: true
      service:
        port: 8042
      image:
        repository: codercom/code-server
        tag: 3.6.0
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
      extraEnv:
        HASS_SERVER: "http://localhost:8123"
    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 35m
        memory: 1000Mi
    monitoring:
      enabled: false
  valueFileSecrets:
  - name: "home-assistant-helm-values"
