apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAx5EnVDFkY3hDeZEGw2YZYYT5+Ym6u2W+l5UEhsaN/p7udXFhrcTRd5TE4jvnp44osB/70Ww5n0hBQYymNzRukh+3PuKlU2d//N+JfB9L5aTxhI2gFBvHV6LIMaCGY7PbBpQdp6CV4UyBdY59DY2l1Oxb39/8kW0VmOZdVA+/MbuPspeXts8HxNfMOIYU9vL0wHUpLUNV/x+gMNMxeJGvTkUcwVfj3Xqzdj0+6E/PcFJqZRK+J1W6nx2BJD5zUBd84aGbo8tU5WCdemGdnhlqzfbjZrN95l9V+uCjjaJ1sKDW5IJaHIj1wlbsWhOq7lcYnJl1y1jo+Vw/xwIIb+nFRZedwfEqoiNTTimrs5WyB/FnlGW35dwf1f9fR3gzrWebZiefH9J1UBRLH9jBBqMeXqE8vVDsryJ34XAsx24s9ImmfoQUl3Ou9cXyVEws3nUKhueLFJ4SuNbcMkWBTYe0TST6c3QCCXKcdYx50/GKfJzwUZgSuVzSQhjZidYKGoJX7VCt3k8x4aVNKPTw/HgOO6VxGUe9bKfPfWoqhYKmy7s2Bt36oJTG1IpVmnPHS8WLwWf/ov0j+zprY1FzVv61RfyiDW7HwsMMrS5arTC0zjG4Z+w+N+JuPGt5Uzpy/xpxU6rz7slYVj+9UbegLbLixozf3sLxX3NX6O30YaxZ2QKLmWTgKN+fE13AKmS7T1AWFluGkEAphCm2jqk++3rEpwBHGJ3ML47jCPsPI9g9vtyI8dp+lCxkZsruPrAWFWJ1/n7rp5YTGxHSrFV0/GuQKnUzib634+XyTeH9jHR6q3L1CYHRoUFrzTarBeM9vDovzc4tp/Xh8i5G1Hi4/woCoPcelEPwsaUMx2gz171TG5LlzkKcDd+KVrk30lgcGlzloTpeSFZGQojM5pYgbg79JVlWkyGAZc2wzc6kkxJxc/prOD7WDJp0P
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-helm-values
      namespace: default

