apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBcZHLjFBhRriFiDSjVVRk4mzf7jni8EKL8QaRTy9nfJ3UcjpB8XgJghX+XPgT1cuXbY+C2QLEJZY1dv8o7wsmm3UoQQmPhpbZ5cbRh6dp6SbE/37c/ospXiqNDwDwGv2wQeUrBdKkD/wuM7Dla80uc9Y5R7hfR6ePx9ggykR+1MYE+q/MJT6QR+2TtFhxaL0qSDHaddtlTPzgZN1VnRjnP+D6+j7PZswaT/ycMm8FRk7BvvQF1eAKGMHB7MDcUg05Gow6LUqP89Q2m1jKJlf86fbg+lOCoCxzcuO+Ffq6HL/wjxBdp6grHshDLKLgUO1DVJECftxSNp7eLbwUnZwRRfEp4oiZnAIqT/WURVL8T+n9mBZrDaddOIv1WESE4AzLvImL16uyMOQHbfNxT39CNNj5Tw32p0sR57tMByYbwhyfj+LjqQ8KVAdQjQbk1J9kGjXkOVpX/+CrKjlrjCn/cUSvp5qsvHFuxaqcdZhUZ/pftkcNFPQ2VAqkIyhy1NB5FKDQ7xKs2f2QkbHcohCh28ERDqiKluU8XT/C0h8lnFxBb3C1ozgohFFyR+0VxF0lceVNpB4uBhZiWZpMxfRd/9mjSdI/w3/vNdiLS8wokCfAIARKu7N8l1/pJpnP400NzTmoMAfDybtYkRe24rMBrIApOzN2SP1d8fx6e3HQn1noztvQq2/C8zWcwllrEsr4IVFuZ219UsA4vKF++EGJwoecqgD/9nA49/JlBMOJc2wozF+pZN7zkbudwYskUOZ5oiEeHsUGNCEeo5pbskmlwSP24UpbTckzxM0HU3vxbDxoFR7oFg3GxBuXblYOBIEg3m+gJd/Uvmd20n5eQR8PtU3z222Fues8FPdILNGMYTtJET/xy3VHaSuG2Mk7JJQghF25jfRGAOgrobSpXr9lBtMDqqg8Uhi7bji7+a9Z6buy8VCKaxjy+
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-helm-values
      namespace: default

