---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hass
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0.
spec:
  releaseName: hass
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: home-assistant
    version: 2.5.0
  values:
    extraEnv:
      TZ: "Europe/Vienna"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "longhorn"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    # @CHANGEME: why was this in here? Maybe because the hostnetwork stuff
    # service:
    #   type: LoadBalancer
    #   externalIPs:
    #   - 192.168.69.105
    #   externalTrafficPolicy: Local
    hostNetwork: true
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
    # @CHANGEME: do I actually need this?
    # vscode:
    #   enabled: true
    #   image:
    #     repository: codercom/code-server
    #     tag: 3.4.1
    #   ingress:
    #     enabled: true
    #     annotations:
    #       kubernetes.io/ingress.class: "traefik"
    #   extraEnv:
    #     HASS_SERVER: "http://localhost:8123"
    resources:
      limits:
        memory: 1500Mi
      requests:
        cpu: 35m
        memory: 1000Mi
    monitoring:
      enabled: false
  valueFileSecrets:
  - name: "home-assistant-helm-values"
