apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAmPS8bVP8gdfYRGG9uUCK7Lkhh4nnmZKfx0zKVMCGnjtfF0cb+m9awYjxv5t2B/QRcEuqWd6S9r2P88xAX5Pe+g5chwtFqmzo+hgJxBZ54O2OaiMVtcrb79MHchDmuxthcD2GCgBOaqGPBMdGrRwalqTvnqsLClliYmt+uXarCCA0mx4B5cikMkH1q+u6hE9HrY3uQcb5/p72lz3kSGUrOmdQN9hp3MjhcF2FgbYWMRi2rCnYZBn+0uezF1ry2fKeXy0mM7IwtIOGCE1gmUMz92cRKeQHQsci00YXz1PUMNBwe96RE6IWMPQYKhmMEqwLzEsc6eyF7c3kL856o+KnjhxbX0bc29wfjaYcqQDESIIVHm4g1PkhWcUn018xP8OsJECfbJtHGeLIm4i8xdC6MvkFVcRXhEeRWIq+LGAS9xBJnYTeO2qeIby3gJcXW33VAusBVdUgbGmYqU/Lm+/gClmwLLD+18jmHljy8vZh+UDZnnmIKHsORW7bhsW+uw7L5GtsEP8s+Q7rga9iowg7u4L3XCEB+EvBiMmEWsjiRBNxN0GDMbJrwCmgkuHQ4o4dHmzKk36s+EJKoM5tGeWitlcVev6VeWVdW2CG8MDTaxwJh6Y9UQSb11eHsUWvBkbhibJweXejKwDpCp5BzoEkAerxZccCZGEbOt2KeNjWXPyWyZ0p8CHbgjEhSpuOVVEzKNbNmdDmQlgAvwULWjxRJjjyM8gV+2tvzAso4bP1KaVqleE5dNU3lacW75wrY4a0e5eR9br+8lYGmGw2xeUG79hmm3Zzl7Do73Fh8HATBxIvHkLj2JMtZxvUGnTcqskD5otKD+HkiCXIpGNAysVpC6PyZUAQFYyBwO9JMATf1pZhRbbvugny+M3OdGD/MfBic7cj1FYZe9WueH/yLxzfQ8q19v/m7Ivpq0N2Et7MO0JlexdxtGYRvkR7a4rBXtJLVjo9d6bfbFHtN6UOcZsX+47QdcA0eXKg52NBv0Qd/QdjI5D6mkZrc
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-helm-values
      namespace: default

