apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBaQ8ZbFpecLZrRPBSDnfuFdWth8ZCg2CUV6HaPd6JOVfMN8OyC39gONSuXNWgDEQ9uXYf+DtRYBm7DEYbQN4c8gDfNpjF+2o1vcN5P8j0y5Kduh5xmXxuo7Vps0GuudRSeq3IXXhbJYtKjQpOGibUHR91F436zuf0NDtEIt7m/CQNqOmG98jkSiJltSkysXnu5ti1NqM9I4b1cgArBvwg8UhcvzOTu3fx9oH8ZOVFuByCOEpiKcNLk5Ky5HVeqsEYf+AuIe12L1c5F7UzktnZIr77IYRKRq4hWtZOiETtO1maCMj7FOiRB6y57Q/GsQLMZxueK/9NTUqAxPAOibJvirjMc0ZZfX9joYCWh75NnK9qKD/PcuQSD1tVq9EZnHBXkOI3JWQVyFk5NnaBb1PWtlWj6/ON+q/HIyTHZwl5hxxx+iYmkLHWjMmomtAqwB7W1phXvWYXYgApGdVE7yXX1ymy2S/Rn7O63sKsrDbZCHMJrY+wz2A8yE/u7R6qMtAojTCx5MbcJ3uYaPNEkrAtkutnAks1sf1f5MjJPzWScdWTeS6P2CQymimOZ+sMFQGNrne+/3vCzICcNHBEtdlRVkNSn0nMKX6bjfuIX4XmZOULNyD+YM7+aAzM3F8kW2IiIZLWuWxV4yHIUo5iXVQqN+0AACio1phPj1IItvZDNqT99dE0qtqCsritt8Ru53itqc8JCzEO6RyOeRtl0HIfMays2+Ldp2NORFsWyyleCcNpmkEL8eY1pUTox
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

