apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgARyVwBf93kFvllZeL4CBMsU15sK0P42yUGAp1YU1QjjpUCy9LUtV3D/1wn3HpJbTpsZV/CTDifCOUaok0uCKBu6inYZePXz+MH70jNtmhAaKShINdVbdBg/Y9v9JWR8faYP7tYa4FMnQL/1Nwjy3HrXO1OzLh9z+fZ3THboak81qAlkDeA4xdt0pVbu4yxdiHk1ruYcY/EyU9bTwTKoVjbmG75+PgpvI69HOcUvlB4zANxQUsT2eg0rruheykSWvSNCV8FnNoheomKYR9A4AYKJvrI9vZ5Iuii+c1LgnbnHjHhqjxZWoLM03BBBbZ3K2Xdxu296wDCbrck2Bk8+ZA819OLMI9huL5lk6Xffb5w4vxbuzf70Bi3+zC+AZJEy1ViHrm77SvDhD1rJ95Fl/YTzgANz9At1+IW2k5vfmqRfW3d/1TD9cCfQ6sqQYbIY4QtTT/3kgJ3kX9bOND8LzJ04HJfAqk2nNbAF9Tov2JJb0INO5Bq6oshBqCGbmq9Yn1obMFWsbEtSgxlI39Maw2FAGjT7KZ0Hapy5X936tiHUiGX8tBVb17z+mHwsqXxCWNaYir8VczicpdHyBfiU6l/UQWxvgGh1nyLJLtYe/8+vV/3LkoqT5y6o0t9KAA/os3eRBbDKBxiBRV5O/T5TLTAaQz27/CV4wE1ONXIPFa2TNhV/xfiP9VAJYdEHcN/kDpoxE2yJgTcLe/QCG6Bk8kx7d19stiCUSJTqeIXAqwac29Sm6+4fnPfLKe7
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

