apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: default
spec:
  encryptedData:
    auth: AgChb6tm2DiIuj1NhfvyAgCgfOtfweiRxUBta8ntLmkas+cmOq5ZCrHPBoUwbdfSR/y7lUKJMJ/0/OcIDceb6Ikq7qfLJC3LG1X4X3IlI1Un7GctNROP+1G+sRtpRhZmr4q3oFXrHfcYsp4WR4+6DLnZtPCcKTqiIp9rHWuLuuW/wwolwasWIYZHbuMwosNn+n0loIMQ/jU9UIg3jdHKQizOMxZEb00kevAR6o7tkWbtLP3Z6V+QIE/MESfGZFHRaJEZ8p9aaEWHHsd2gYsvHz0Qv7M/hUfk+dPimb7/j0k1qallg4RnyC2IlwGeau0hvhJSiEXhCVQwGm5h4Je69P3qZUArxZKGN5FieUEhwXBeab/XNzhFpstABDtes9Q/R4W5Ab2swzaDPUafr24XIy2COslOIX2gya6IKybMM7jlUYVTAWeJZgTerDQ23vByLY96hTS9EK+Xx4Drrz9CwqzJO9Ecb3FCHI1Osb66bDbT9TpP784ymjtf5ofHB4EqNFXsx65/GpSE0MU147+Q8iPKzmcToLKwCmes0m96kEKj2dsywi9RV3RL31i4Vv5Ruui16oAWK3lLKbRaM+hSz/v3g66Z8ctujnGfHiu85iY5fIjlkOlt6HvYSUpRgCpY0mBuP9/84HBDG6Id90jB6JJk9mJB4KOMVGp87SQd8B1q1Ru2xvguRNW6zx7yic2kfFlDRP+zbP5YoeE2mRgZcJ3RvXMAgIQ8ZYAsG37GUiR+KOM9PuaTMJce4Fin
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: default

