apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBvTUJmEWf8cusJjh/gJ5jSKLVKST+BWx603d4Y+SfmQZywXtBf8wPxQhAZzuiXWhdCAA6FXxx43ZMwGYxUjlK7+JrXr53dIQj1cY10+hSbmfp3+yaCRZOAMbGbiINFNLu3uOaL96oIp2XxsxSadIxX8X4eS59gWhf+DLhQx6hHndZ23aoAZmb9xfrmpCcoBNx7fWSzd1iP7sr2JgMK3wT5q9GU8XPxgLCi2zB5GXx1Jrm6PNZlaBfHnJLUwYZhHRj5kqdbGsNuaGb5Taoe7F1Zg00If+K1pa3KpEBmAZQYZ0VNYgQD4daOwysP65S2bYTEniecHYyZROOTdDecEfS5y2v/2x6O618aY2yjhwdQR9R3Gwf1+y6mvcTcsfazLorIOek/1a+wS9mIAfv5RLtE6jWIptChawIzw1SbOFr8W60OaUywArMuTEeD/hkksE/W3el0PxPfhrsv98MTrx7k9GUNwjwIp+9CCa2ACN6L/gzmMqzsrub0X9zAV78sReSjrWxqSGzO1fmmof1v6We71U1fBrj7CBf8yb/5IPsT5JNHtSw4W1lPDsmotZMrNLBw41kuIlM/OQMnqHXklzhF56u06I2MnhQnIf0wAIXP+4tx27ZL7qAunP5+vwPKT3rCl8Q1MYsGwhJLZT6Mw60A+ttpzqDQviMTC/cmv/ROCbbRasZHerhxETcF9UQz2dB1wJ/hp3U/F+54zONf2ySzy16yOPKc+IZGWA+sYvZ2MH4eFe2vutO2Js/d
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

