apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: default
spec:
  encryptedData:
    auth: AgCCcnCZ2044c2Mbx4ojxFCwvIrSty3Du9zyp7A3l1jrHyo/dBz4rnS0wU35/yBt81PtYXhnZaAf+rdZWoR18z1/C+ighUSZOGRjsI0QDOln/bbHccOoVUuzPEhJyRiz5qL5iIKjGfATe6SdPT+gv4hniKdUvqlOC3hpY21+eS0VxsLLT4Wx7uozB0VITLw4to7MQJhzYypeKqvQw5j6WealEERTe+BuLY1rfXlrlOjz0lme6F+017JW1K4mckztyPBfFo5C2B+QGZgZSxsLih6mUUNDs1lFxP95DngKARK7Xp64aN4BP90kH8FiR+iX7ipEUdBp/VyWyTCwJjxthAvFw/64qQKP/elamX3Hup/mfb2iM/1PznMSkmA+EJrZuy1NtFb5gLRDSMpXtJsuF9yoYw9In0+o1GvSPii9ujRFjwMakfv/wyR9FvGEcjJrvbH1mRd05GWEtDKIm9Unq6f/P4qX7TtvfLS87bwG79iSINDw+uvVXqA6hutBiI+zlK4bR0Kg91n3jwWMnuBDaSyysdtndL+cBL/iR7KjRtcSO44yIn46fvxP0js4EXvvHCYal2ePansrjXH2RD7Y+NDAH2cIH4pHvsUjS0RZbRyBdMlGT1kgwv63i/aIN5VMMYfSsSTnH5gnd5rHbjZicvyxh7CmEmCfUFEn5zYc1X2hbj0u5VI5ROeNzhvLCczRp8XSS6p1RrCySAmUpNXPZv4jPZkJfKScnSsx/Itp3mRBxfwZ5zOumQif5Dab
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: default

