apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBurJfKuQjV/QGJ+vAJc4z4vEJuoQHq0t8oOjx+c7o6WZwYXHmkKKmposjuJtXTImvo0Nh9V5OEmYDzaQAL5N7+sQWIxGDTp9NAPjnxwERtbnsGWLmpeIJlIgrXbSzcO1nOgyOyGJo73G52vknG4asTYKRvkbk/B8Q4EFdcUntXZbfVmCi5K2smwrL8r1jkA90WxGKeBJTcdjGUGmPJTRzz4C3DocyJl23fIA+1EuxetHH1kbtZkwmLrDqZZz3s3qVQNofLS1u6o7c1PC3BtKxcokP6mI3vA5BMqvArcDK2qmBbdsF/+Ru1SRFULAKJDPdmhbLtq1w0qt2SudYrPFmPyczrr2zkLveUqh4sD7X8uv1LJZlomG03JFUqg5cIDyoDTy88OJIg3y/1Kfz4tVB+JZuwjUpQcwDO7zxBjbLKfHq0WEYsyRKBgc7lPNAcxHqRcEPc2ru0/c6jMxU1lzCPi9HdmFtSNKaDWaxdKA5Jdm/ipnQO5JBbpZAo+rmI5plgkM9aW+wLPXk1h/9MrejJ6kDjBshwvD5YrL74XMj9Xcv25zZOYknqnUaaTHvih7I12LIEwZzG5dJz2Gd+4aKmcdwZcyP721viEVkPHOGTkGRsMV2iKPmU2FuUm4HQyd2/3wIl/u7B9wgW4FQuD20v04Nm2KlGHmcgSjGIt8HZLv92pDyTiupe6V5usikeFLJDHsvyEV9OhSN0BzFGl50wnbVqKnBmuDwBr4p13qzVQADJq2qGOaJ/VU0R
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

