apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgA0gEbGa9WkYKuibhqtEOvH92zACOGuP/iiLmc30D7vk5yGnBsxI5hW2ZFJV9CiPxD1xNxnkSMct3Xi1DiZ1Hrmh+z8zRZEtwchVNXXf0ft2CSXs+CR4ZizFmGsveWc/Dr/YE+cw9GTgptRoANmu+J2t65ppeWGZzehOafvuHhiFBeDw4bBLSaZgM8c2nCyyNKWBtw5jea3T7+HLVC92G+mh+snEJZy8dbgwH7Bagp/+L+xvMDNToNvFc1o6vu1Gv/O8HkzmqSAEZxsN59mXAyH/JEKWmX4caDFBPHZPXRwiALim6NjzbxRyvSEBifw2egznER1P67v0XH4cRKPUFNcQtwJ03JR0w/d0AfmnHiZiADGQ5RyKVnugbk7vY1X87l8p1OyR6lmR/pMzS8FrWGMQxU9X4fkpX7vo/8/ouZT1H7c0QkHONvm7bFYEYvo+Qg+8UIbKPog6/kbsSk0loWbHWso0LbzIPEyrXVBlA93+DqoygskVMFPWkeuVNn3gEwk8Ou00MEua4iYc3ZNmeCJuKjlZMtMqOJF2xuciATZkvCtUfzByrNHGDZEoY4IXFOuP8b+DayLiec2TJV3giLXth0vrawGWxc7QiJU1LcvlG8K/RmU3XA34w1bio4pu4tjqNQj1eHQ1IPJsMQ3GJGMtWJzvsiJ3SAaU7zw6MQR8bkWbDImYKklzoXY/i1zWdFA5/Iw7zA/AyekOUjjIvGCnevRxCzaZV34qgO7FqJX7RLLaxA5Z5dgXJ+n
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

