apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBPS5/30+6UleWGq5eX6Agbi3RmmnrBovKnksHty5CoXD47wOLxXPQy12PHVxuM9Te7/yZZheG7FJMSDDPh6v5Aorv7CrY/krPegTj8DIArYp5cnRLjkkXylDksTYUfHf4iD4jLNsUppzwtgZWm3SMK13qIa0Gs02hRHWbz6FfLja8P56mSS4LZ9dpzj/7/0utAclAvOnoDqVK/Oa5HDQWpF2+7hfi2OaBG3FkmKmnEIQpPKT8KNtngfy/hrLdRu/DoHIwYjEDkkQMZst4M6kMf4GotLYg/N5j+lD4MrqfltQ2BQjJFWdovFTXFoBDlE3Z3DHlVV1ssxU8Y/1BLSkC1R4lDBHhrCgV4otd/ThBcWKHRdD3q6ygkuCZFW9iuit2deDa11jgk0mKqHXSuK1iL7E80lJVMo0pOF5RFs8Fdsf9wBMq97zLXMhR69MsbIjiW+cr4dcqPixTII42Pi7J8VEW7Fj8OQgIgoTeRdIhwR5lgbWI3Wu+N4DraRah7qgT+pV9mtlWkFLovwizuo1nT4nMV9SsZG/OGK6mHzlE/iHxKWYayUa+jEj0Y7NkkHB6VfBUj/41jDLURUtfrfzoDaH7tlT0tTztj/14YrMbOO4nJC0G9pURTGIPtUwlciP0uqCu3UxUWA6cxtoNnjSvQKvQiFf05Ejg8gBEFr/cqi0v6BYYYaZJNBUsfYT0seg0QmWuxjlih1LHv0qYMW6yL0Ibv7Chg1aviMqG8m+Uac3mxzQSFVh7w0goX
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

