apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth
  namespace: kube-system
spec:
  encryptedData:
    auth: AgBmkrFwetjRAoeR294aQUzxO6kJUt/lO8ZwGQyNJk0hDS7tTWaULvrNigW8P6+yE1zG+Z/9FFJIF1SGpMzchQsbLCevFBcZ209XJH2uPMnDW6ufk5T0u6/0LBdkzkPTmWbwDYu1+PpL/Qz94eSyCf3lZkEfsnRLuf+OAnjtsHMejxOiDzdbZlN4tkbw7LN4jpQc1Zb/pEIKv1VCDenzJRSTWg2xh+O0lffXQwQYvGkXi7NWjaprgOrA5j1ngmLKpTtShRvG2VcqavxoqKfowp50QTHx4JGFAt2Onp8H85I33QD2Lw2NowP30gq05lTDYblFV4Sa7c13Myoml1wQWK2TdSdKOAttcMHnN+hjRUN0vf8we0MJqdBJSD3oXu/dtJxxW8Cv1jPOBzk1If67yjzSUga2J0nukWtVWkeUaNUfrL9wBcABXlGMS6vpymwrXsrmyLJEe9gGANBQ9XEq3D6+XcFcY0bV/AsUhWQSIeags5a5U+WHGn9oa8AkTzoNWY82NzVp1gkxIfcYf4M2fQDgKaD3OeQ+JOJoGQhrSPwuOUv5aYC53nwISDmbZ3YWfknzA8WF1f8KSDL8gmkc416fl7QEjh4wciq+ot7h0JgRKBgba/THhecXltHHqAURKRSvI44za0jy9i7l91LnLHcdJ1+xLNA7uVhnqWa2uGWbbBcwqUWG7y/WwnFuPHvWpVGvFp/vTJj+GUZvGNSI7iQz75mt6CqU+VE/KiamVhHPY11oglYjQpX1mUkm
  template:
    metadata:
      creationTimestamp: null
      name: traefik-basic-auth
      namespace: kube-system

