apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgB9efjb4MFSq2jj6h93mk4djHX5CLjUArbkL1ZXlSI80ePOtpK0fuyLrAk6RBVfqXJZmrkzfwZUCeUO0/lgD6i8eMWzT8h8/mc00nsOdDK/78G3z3ZlZIgj3O0Aie4Npj65QVfONg+RyuS67SvvnZOug4NsUEj16o/Tz51eXDOWjUFbh7Ws7tovhrCqJ+FAN1pa0MeEF8syr2adXIobjzPbB0tL3OeZPLez7XEMAPZAd6z8jekQx1jM++GxYn4FLpEA1/rlp4wGZVCloWNKHXH47NR8pMCGl9YOHIFWAuta2eCf5wXto9kkJwCa1VLUjjHatwCesXoKBQ3DRdC3v/mCiA8LQig4QfFRiCL0sXKsRJMwQRnbnVIeUPDghP2bfTxZ4dVjgPjqGEPyO9EARAu9RdLr8BQ9Es4/mbzNV3lnN53CqSUd5nUx98PLu1MV7Q20wMl5qiJ8INQH5D29hUcOwTtcUIeeok4IWwur5M8/irXAqI4VhAXyvrM0uBnFlUuE9iFISmrUz+sLL6m/Q1mKYAuOOjPmqxEbrWoUeAGKQ5grxxlDRU3+mWWzodFqZVd89mwlUCT/luWTIP778tHPx8TjScH7ywekvlRQC1RUst4FeiISAMz+N+0qrcnlCaEHrxECj81Ta5NmyJ5ReUPziLRhntRp9Oaf3Gf1GNungEwvIffaiXqcDjg+puHVl2apw2bqnxzKDY1TTzrSq5GXR8lkj1L1HBU=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

