apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgB1NUCnrjBdPa/0UhdW319ezR+dBs9mcXrkWcpbFjIq2hNrtbfvOVEaPjhQ7gd1lUsL9dopiVY06IDHXA8oPH8aKyqJWvAZU7tvroMHrAzV+8X3FLQ1UPrtVIaKFq+K3n5W4sIS4qFp46SF/cdCY2xMp+LcUpM0eYGSXMn6saPdDjqIQQWOVJBjAVEEKFdhBZsUlj/s19tRj75ckty6PaGrx5sS8YNEwe9egaDq6qH8rWg9l7dv0ywXwASIKvuqArDoabfvWm3AIdApZcmPNU8FinQkMt0kC9JIaNaKSQ/ohgMiH6Q/voDgnMQHAZlRzoRuhwBgrUwRXfesDeBHOOj1egQ4azvhYgygvXVMFwctGosIowcYvHCV1m4L9s6CQJkgvfpBMXE+LHjW3VVaxTcqY4ib4Z2dbgxYIKBYId5gsi0PRv+BIHIX72QSRh+SxaQwMwfsnD+N33r8yUnnAf6cQAPKE/+9Eh3ExiCyg4jQo73zfX76lpKiDawA12iozvTkfV5FTYlIjZMjKZAPORgGplY0YYp7rY4TRZtVnzAd1tQpWvJzQDRC4RDxYcmu2hfkOW0coZWzHD08XAwNNq6x50tJXBkR4fIjOT8ETxMWq7vQi3qA3DS/WXHGCPs2yd1d70h9+hwvANrbrmeEWpysUyMH9/A0MANVcGVay6cLBTXJgRCRIM/XFoqRRD4lFTYCPk+3yTU9JslfolJw0T0O+8r5W91YoqQ=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

