apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgBEsqq43JbK/wdWTk/U0gXun+N/cmqPGvQUgh+mAqXbyrQL2SpYMAQepyHHYlRmD09rQc3gxvXPG0AUSsLRsQd49kwKhON3QBgSzIZldRbC72n5r5JUf5Qyha28F9M2OAPimqKMfHXH5rtbj1fjOfRK3le67OBGE9f3WCoRShbJItLD39YJPlpnuEmpOH/XBks1dXeIASDiwPdc4PccbwgxQjWM0MbyNWyz+VwVym2NZgzJw2J12DbjNlSLEduXL96RuY8ELqjLoykKqvaLREliodHbufkjmPRpjV0w1cvlbVyOls5fd+g61W59p42yp0tmW3BmIX2HIZ3E3wHeCkec3PVUqi4jnCD+kKLxPfpNMkFWiKVUFc6X7qbi6j26XsOUbquXOLOiIoWcSe26A1V4ofXXly+F9S2RJJTaXmYwASF0dseypcMzc6FV1FGUSkJL+4+7PZ+QZOwJW48Rne2cU5aCQ0ltduuDyjAYOZQaPn05EYpl0YALKuuiFTyJ71A/xZC/iuChFiLMOxyMgfSSPfwepGFpboRuzzpADHwDYxn7QSQZiMpJ1JwNkKGbhn+ftOTp3r66DWcpa9K6EWWAb/ozNhXDFwfiQ/tDJeKlOoVAYUhkK/Q6CpCVYgyvquh4wQHfcIaQiYr/X/C9xrjM9/FZSu6G8WA2jONGu6sTGosx0kcs0/W4v0mDboJ3uTJ+b7Yj5mY8Bb/gNqFLWRZkDcKf1NOKoUk=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

