apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgCgU7V4dDALfArnrxb7YKxBxPuPrawU1miwLuLOYZhEITflBVQ0Ecm9IPuayovDT0gbb11TsdyWoM3HBTdBruLFjV/D/5CwzZRvsHyxh7KVgrDI073jgn7t3Jxv2xdszUzA/3vXeRQKMlbqsUoZn+Ds6RhzBbeh4OJRWdJlkcFGXLRYZQCpTjFW3kXrYYOkm2UMP0MoCxch+FqcVj6SYS2hSvcSZXLbd70nGq+fwAwMk/Z+jaJ8r+eecs5wC69NP4KALB52eHz4Xy9Fx14wSALD93M8ovbL2LBDO76ER9cNDJX3IgiGQiP1oxlQx2wRXU2cLzLIXUr9IePmolKFk8qhMyOFGg9JDyQ8P0qdOSUTkwQAipR6DCpbPqdH/3iBbAhZOCouzbSReFNqRbolXDLjWpWMiQo/4K/PyuTU9C7gwghahi5ujOQd+lycxXLCKhX46D6w+Oc7BssUgmaqT8tUxwyekBHV7pVuUsIgqFLVpgDbxIzUhYxAhwBz0+Zx9q5nJijnYh6CI6fsz43W2/RLOSL149vTgUw9WwMHJhFRKG5ceZoOZhu2R6DEJ3S1KnrYb+BlEute/mbDd9rqb3Kt9U4IUc1tVpGDwTir1zY+1Q4ZAb64hmjhjLADRWeaecIju5qamJ+woBAoSzPvJ9kYg7RYIv9KvCdLd3T7fGdBbHHBhyBIAQhy1d1bmxvm1wHCwxh9DI+BSZDG1L7OmzMAFxgr72Uxcqk=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

