apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configs
  namespace: default
data:
  dynamic.toml: |
    [certificatesResolvers.myresolver.acme]
    storage = "/data/acme.json"
    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [certificatesResolvers.myresolver.acme.dnsChallenge]
      provider = "gandiv5"
