apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgCmApHgt/P7ZBYrzn9wJBB/7FcXDjeWc10f/RpWgcAM/f2pMGXkOLufGEC6Ni5BUvkQUh05MIJgQ89bm/YwBXuM95oasXxAGr4UHuYKwZYC71yeCSMCN+3ZC1ciI7odcMx5rOb0+97L+y/feykxvLLxDRHHyg2sJGbrxKJCvC2mjm14ruDDX88WaqgGBCSiA4MFZZ2vaXe5pxerB2e54J25n7Hw7Z7Jn7fILj0j5d5xzT3PkGIlRwp/h1F95VDrnqrr6GFGf2nCqLXHrSXNH9UC/FmydqW8jNn7D7Pg8n22whFOCzK0AHXX56T5ccfBtgGS2liWiYCduwbDSqIQ+vOsW8IRexSKoSEYT6wYmdcyLK4x41DmHENCH3sw8++0T/hvhpDw4PhceDt1gJlBaE8O5TBaDG7gyEnwWbd4dkhM204AYi2cjkIIOqI/9b9JQ3usfpdI3zD4RGSmjTy7JWCJMs73wZgtYiQ126L4Q8PB4UGiUMR3I8ZXCmjKzL7hPlhWBL6Nv2bBtCYK73u2cOqqhJ9Ml9DbpLcaINEYUJSBnV3F+l9Er62RHgqyUC4Oj0DaryxKce4NHOOYhJgyFc7rbex9eLlRpJhGOh7fE0Qx8NtHR1YfrnCJt/v5xY13mrxkzT3NJwHbv26ioLdDtztYTapaFCDunOVQ8UhCozWOgJk+I9fmam6N86iOMHbVTAzTmGRyTxuFbmdY5hfOt4j7k4w2xShu1aM=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

