apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgAvZ2rrJMFzJ7oNxMurEVE/FAJtCHn8JTVUtW6yjgHlCYkwCQgi6rM70Vy2W8tFxk4fL7u0RCKgpomxLz1+eba6CAOM50W+JTgFFl1X5pjJowflpVRpcuYXH6LQJbmGjXaLcABOoOtaXJHS5QMxIiTH4SipuObzoTKSaHplOKCnSeLkh75/sJAy+uqUI3WxPPmu/2LPg5Tv8Zgh/D176UO3b7u433SLlK+s813zODjLiCoNjf4K7j4qOYkvYezHJk+lm5DT3Lu/L/45aN6eRhGTFblBX/oVPCvnlqGv9UuUyeOWt+dV/tK0VxDxSS/kyv9PdQSU+/3ummm9BzuZrZzj2UqWg7lRMaNfxVpNgXl5iPfFufAb436Je/LXFhSKCgpKqO1ycWuFTTyjrHX1pA9BEPF+5zaFx5L8IwOpCrYoE1OMgl2LJhcn8+qdiToo6dCoBAivCuSPb+BIkV/n0ERbAYSdGeRCTzQWluSiuYH9NTXsbPBXMhEJB4OCpgdPAgrBd+vEQAVR8bv/06q6WjntcNlOBv9WrncmcUXQov80ikdci+lNjyqaNW/dokWSHWRKUzuoMChvc7QYAI8PsBjryM/ieswfrXcFax8IncUZ6FoVIASGmxAFsiR53LJBFXs3vNjZJo3B8skvVP/7qjst68D4e5FMnkSupHHfKp8XAV4oyxhLUboAs3FsUCJiVqyDDZcyi9/ECGMhMt1Q/uda1BIQFxaQz6k=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

