apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgCQ4zC18ULAmNcj5ppGFnkMp/5jCd0OI4SelqXI2t/13X4lIKKEpbOp/vhIRJz16hsxdvCH83YpidumeT66WAzW3dXbraSrTBEq6v/QoysevmJ9re9TFjfAkkX6lscBlrbNI0VxVmjLj4dnpFh8TVotbaI7eMOc9uSBCVqnH6N56zuuuA8zu+Ax7HXA1Vb/gM/NcXUNVJV3Lzpos3WgZeUusACMQNteq84HhCewh5HibEzXMF6B4g+wiYTtxr8Dw2ZtDaAGofc6jRf4HIdIjJxWefB+thKsukUoqWyix2L4JzWalDBxLVOM5L/i3yOoZ0AnXdXoRjvW4cvUOVvZmvrf88RYLMTkPpYim8iTawk15ZSsVeKP1NPs4ZSOI5Kms3vRpNOnVqMUh2kCRD56ctr2hjcYjqHG4Q59JeMnpr2EqIjiV2rDJD1G4q9mAxejf+Hv/4u+3TdYhc8IPsgsTlQTD2054mbpkiHAbXZ4akoyibtIgpJJIM3SHC7t2LK+n7tXiNYiOG+qL/KBuEESlgKRW18Qf631La6PBNVxsAxF/I8qv0BFQ4a4cobN2psKaV77FnwUNbsNyV7GoXc6T93NYucE7KmC0bx6UAAG3y2opekM5nLqbmBhXwYFhxv99PZBaLRxkn+ECMIcc+/wR8LYV8m4m3etelHG/reYCoE/2lOd/nJLp9I+1eaFNL32IViretyrQD+mSbG9xMmILRD0mbFuj62nHeg=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

