apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-config-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBec5TG0p132AgFgr30dPuowMNKRkIucDXQscGNlMfpB5Qe72lS8DR45IgLJ/baro1oeUp+fzCFEVsnO/OTOUY8eOvn1bpEB5OAYdI3q52c98u3YIV3hkuUA3v8AWMsVORXS8ev1q2KW6gOpstTReqUEuNzFcB7Je9FgalD5kqilI3viOgzEiPDqzmMh+4rRJgmMxV9P21mu7PuXDvAXqxkucwuXkV7h97z97/dCvIdEZY5or4pgOueqLocUphDriccH2YDgiTQHte9CkcGN1g4MdkN1266+Y8u5cATakmls8Rrm5FY/dEnoKZa6gWvdXMCJRcTnSxp1dqm/HfIALvmYk0M0dqKdSJ/MfcMxHeQH4Rey7G2QC8gFhFBQ/N6WYlOBYzfaOflaT5vrNBgTmAtYaIvmfPzS+1hCT1h6oUZBO0zG7ZOjVOQAYEef8wYNMH//eiLLMB9SId/gvWvou5nY6D+kHh7c3/9+q0KPkLmsvOI5kTUKrGNtXk3GIR7dS1teB3ARh+xFtKk5pwz9DkgaNhMHETXO6lKeop4RQi57Ba2Aqbz06aXjTz5dw+IhxR3mNFOUWNGHXekF1z6CKkSDMwsyDxhImZLx7D0pCyeww3BlUEKB0536yZrDHw6mI7TohfRMcHQn+mWcdIcyA3c5D9BVwIjE7PlirQNeXOhzP1tMQ29wMkV4jUhzytoX8lCu8XHxG3naQExL1CWaRaDPid9r3wspb2nIdba3FHRGs2mJ0ucP4vvQbAcoV3AlPJFTvyU0Hg1dtPQNUjtmXQ4e9yfk1sMBW/8WSvQ4nUAiAiPfFTYrwUIwCRwwqw26PIs2oYPjfBXXA6hQZb9DjlVCcaTwTYIOoGy3wI5kmkFImS5x0ogzP1MxKBm+mEVE1Sz0RKzPVfn9U9lEzKKqo3JUNsDi8V4wh/UIpEcvzaV+04WGwu+FEZmq/jxx2o8EKhjPq+ZGAPRX9Spo+7YMnUHgcTUBWG2Tj6LvAgkoRGNBBhnSVFnPwqDG1eMldKZh+Q8bAOvu8Vkhv4jTrgZdfH0gi3SYe/CbVLigSDALu2bheatsKav6ldDzuWr3wPa1ILtP7gU2pFI8D47b1NO1L64sjaHngOtbCQsemvCDK07/CF5sl0ieXEj+vcpO9Q4TM5YPSf7vlTEWI4EuHyUZZRax0AZTUcFhvMJhRDHOW+KloPmqwSG+/eERxD+2V+X08E+PS6/UY766ql/YhyBaVgXng==
  template:
    metadata:
      creationTimestamp: null
      name: traefik-config-helm-values
      namespace: kube-system

