apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgBjGtY0vPLii7aKrcaK8DGa5iZH5cj1yts79+IycfDgAWfSAU4UWQPFD8oVpHR8POEX15NXhi+IjIl87/82253IW/a+o0M4jv2YmIc/g/uTmZ6W6hr3ei0eVZyckJ1YosJo3+Fw7vM7EqcTW+nbYsi4dOdUVkEJAc3XA+rbfAVe1KGnSe/n4ywRi8JU5odywxEf1F/78ryaRdEY0uoX4F1mPdqIrK29F5KcBKAkruB4pu2CZYK5371fCfjB4W40fhXeTSEW3mVzpOgSGFkI4/XP3eao16v/e92m4VX+1Eb4Xr2WNCgyVM47q8vIqGlPiwoz1IfVd6rbHb3HtVEj7tjXit2XphJYnGn9PmRFrRNhjaa7HzClEirt/hxFwWKxTYb8x3ZI+MkLukr1w41r5LwX4rJu1u4mo3hX5ov93U1l+vfcQjX3iFDTfaIdu7+EXmG7A35eekOQGW3DGI5VBLuYq983SyUUWHn8S0zDDqPDFxlClTARXHl16Z4ti20kAhXI61lQGNWhQdITBcLFfVaIJKpXYD893XmVuoFd6yhJ/fplo2BfzDj3UlnIyf7J/FvL2SIv2Sgj5cmv4mFY/G9pMUOAeBx8C20Gfa9k0sGJtv6LUmgVmItOEwcXwaN5FsNDmiilbDdw/4zZJruTJQsIm1nene9pWQejR90qhf5TnUfREdNOFtdASBx9BaO7L4n+lNyo7HI6ZJRf0zInC9gk0dEGIAVrPL0=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

