---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: traefik-ingress
  rollback:
    enable: true
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.4.3
  values:
    incressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirectTo: websecure
    persistence:
      enabled: true
      storageClass: "local-path"
    logs:
      access:
        enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    service:
      externalTrafficPolicy: Local
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
      limits:
        cpu: 300m
        memory: 150Mi
    env:
      - name: GANDIV5_API_KEY
        valueFrom:
          secretKeyRef:
            name: traefik-secret
            key: gandi-api-key
  valueFileSecrets:
  - name: "traefik-config-helm-values"