apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgAeGxVPo1fuvrn+/i8e0n62DbUx300OadS4asqMXLJTdIc6QmyCdR5vroxplmYK95mEOVp5ewO0LyKTKt6hrfQg9vbBsWhFknOoMv5t65Zq6iEGdZOeEMSc2vVf4iVlxOISLMJd0SLnPv8Uuhq+VLW3s8r5BM57Fqbj9NPaAyvSNN98igI2f3S5ZMrnuxr6FpOYkZuWGep7jAOLlfY3lYEUldBRtS4zH0HvRmtkDOpwrqD3+IAjCUegpj7s6xABqkTN1e6kuAjMUmP2YxShrFx7S+7eQ4kfcju/HnWg662hKYWkHALYoFnKtiRrgbMNVRBZ9z7HpWiFelC7JsZgkVBevURIRhepB/qAPkJVjMano2P2snZo2lt2BMsfenwbk0v48YRP/0fY3H5BYMAW5GTK1KK0a+gwNxQl56ewwcKuR3U+lhVyZtQb5YnvSd0ksf3KMF4iaeZXwkYsokWvCulEQKnbmsaQtK+HSHG40IYxctgjVWUdUUy2jT9gC7TKpVtZDW/OQEIse+GKVJojbliGrd/2Hd2GYISxe+fva88u+Kq/XmonQZsfz96xb19tooK6b182amEHS/3THFTZZafJ7EqXw+rKYTfEqc3Dqiws9AppPr4XAh1cYFhXMOiqKQQ0MTkJR5dnkbk6DCtKCuWA+STcL76BIO4Q38FImG1JXL58qffRQqdfbo0P5HQ7HnLUrJI3FBUEUtqNZpwNcIfA7nUMiB6ic6s=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

