apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgCvENBrF7rPvNO4FYlUfHob/u4u36bSVc9mvQQhSt8WoAjMJFIwXvwQmK2bkSpi01teRsgGCiH/XM96vbSu4zX7SPbttoZU1UzHCxZxwBEssk3q/GIVhjkmzayNRZktF5KtwxJhFtMmFUC2qAicIGyrrPw+wmU2yoz925Z8abkqt+rF4hajp8ZfGFLZ41Ua/rHKMyHvJs8h+SgKN//KaQnzXozRtEPwNpjC8Zpgd30lebk2w7YEVVs40J4CrbM4DOUldGawSGYN4Q+pMjHeM7BtDnMmCeB1uz1fDl8xev/1ZKqFzLr8t62ULyEMdFrz8VTFrWnqe2SSrisuUZ0pa75itlgdEOruHRIL6FNMBk1bE9JKMPXN4UiC/KbNYb5TJ0JLt1z0qpmgKJWclZ46AokrkMHQtfHg6/LZ+yetm26Px2eN0ktdw22qZomef2aDJhthrIIxi/X3Ao3c2+kQXCiJTBg3Usnv8yIgHi6+5ULomMefvkQXVD0WLQEpAFcYcZ2Y7AtJA55O7PxslF7Foz1WNfEY1aJjEL5wcKRUrK+ngbw/5qt0us4DrTifW6UVFv4d9ewoQOVMW0brEBkgYxQRpFYF70hViRHzKDXFRzZ2OPHfqvcHidLnONRokKJAAbPCMSoDpEUUueR+e9DdRk0Rbpy7omTVI05pXckLD8lWGKtCdb57tB1OqNjDLwpv9tQ=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

