apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgB+egaRb6u3ShcBfJJ0z2dPbUNdbmg0W4Byn1rXcP2AQSASTWzZ7voi6IvJjqnylOkGJelEfFuZoXttvT73R3x/jx24VGAze6aEKDOV7B8sMlEHNsTmqaSHGDpcqvb94kJJ9fPkjBIggvocFQ5ulxiEU9WMoHaDdGpKB8Jy/PappLnfBmXqf4x6O45mcUbxVne/mM9ceHyN4Wlqh8AxoZlJwxqG+KhNKDw668agpaaoqpCz3WZdZkN+nIU1azcVRNbaCYoJRZMjBTd1kpz/hCBMZ+5dv8cxGf8UaziIQ3Vhg1ENkv3VYT9VjUDJcquw+8K+pqeOrhrN1Ws248Z/2VDuGpnkiPdB8Gf4hg1k+1+86D2IyPbbprG4O9/JM4dFn9yPbN+ck8co8Ov3U8q7MWs0+hEhRNo27rd618dAHu3DvBDDP+tK1t2qmMJWboyVcU0lfv81ozVZAedmBSJWnWx5wJv/iV7MzBghUxpzNhxfDdMd6mngnLQ67s+XfCWaaHq5fjW92aAgdUWyrI5oygPM8dxO7c1NndY+jyJGGjHnqlzxS/Z+hlHIADMTEZcbiNmps+HxgtBrvgBSXbIBYWPJ5V7OuMcfZ2YGyGZV7znVcspuMPfku1ta5jsDBy5akUJWkYslmrc5m9jwFfRxoWfKvubDWzUcQlVzx4uaZM5zrpLPIfCBLokBvjm0g1kvFtlMKT+1ce6reUz6laaD0lm3RsjFimc4Qqk=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

