---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: traefik
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: traefik-ingress
  rollback:
    enable: true
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.4.3
  values:
    #
    # @CHANGEME - add proper traefik config
    # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    #
    deployment:
      annotations:
        linkerd.io/inject: enabled
    incressClass:
      enabled: true
      isDefaultClass: true
    persistence:
      enabled: true
      storageClass: "local-path"
    ingressRoute:
      dashboard:
        enabled: false
    volumes:
      - name: traefik-configs
        mountPath: "/config"
        type: configMap
    additionalArguments:
      - "--providers.file.filename=/config/dynamic.yaml"
    service:
      loadBalancerIP: 192.168.1.5
      externalTrafficPolicy: Local
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
      limits:
        cpu: 300m
        memory: 150Mi
    env:
      - name: GANDIV5_API_KEY
        valueFrom:
          secretKeyRef:
            name: traefik-secret
            key: gandi-api-key