---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: traefik-ingress
  rollback:
    enable: true
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.5.0
  values:
    #
    # @CHANGEME - add proper traefik config
    # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    #
    incressClass:
      enabled: true
      isDefaultClass: true
    
    #
    # @CHANGEME - Update loadBalancerIP to the IP traefik will use.
    # It should match a IP Address you have in range for MetalLB
    #
    service:
      loadBalancerIP: 192.168.42.100
      externalTrafficPolicy: Local
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
      limits:
        cpu: 300m
        memory: 150Mi
