apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgADDO0WYsl5lDkskMevBRFKuGI7ywaDLLMW9iNi9+Bqx0w9lPC17dWQhQTWmleAoRigraMgtb6qSyGFVfDUwkoaPFFfO6JUB2s2KjcynNEI+AaKwr8li0jOIS3ord/J2uV4yGjHQuCrfvnfZ9eadv+PBZNoZLRLgJ0wnPjzV1xtDsqBnTRYfpm1M0QqukH1V8Ap1mMFqCIwwDIOVmsabJd7eNgOEm94hYFj5VUnjgfWbW0JmYCexD/UOwugVD9QkLmEQom1dHVyYblHuy0C8iXrBVJOgeBlaIEoBnNjA+W2Dsyqto6S4RO1Wfqr3FqPE7N3nD7jCoh8VRXvvOTHPcZ26R+ST6YQO1qsbBFnpp6cjpAjKvKKW3nvsxsoRNZyqpzUe4l7s2PcV/ORvWy1aiKg1qeMq0YEKpHR8g83vOEsA6OfGErf0c5I3egUHgR8tg45yDpyR+CHjpSTfbve1Q0aiYbKnS0Z29vavkjHNXXJdeDJf0thPBKCa3K2c8PmTzNZctlFLyONEdLS6jE6v5jOQt2mc4GbYXLlfsRBp75xPjR2emYxv2ktRyYNPcEuAVyU+qc59GmJ4ml/6hH5CEFSBgt1QSE+7S8nYbNSKZbtgpeasptYpKn8LSX/IyZeKfBNoclD6YGvJ7UiS2uqAMj5+jrouvofEPOVErf4d2VeW9QeBiYAVBhWIBB2XSuISdgaHeCijoA+IO7rordPzJfdL5dG9+TTPoM=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

