apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgBMbTnFswAqrKRwchYShG77tUn1iwWbiElTqWgvrYnEzttzyBLklCfKC2VTH6lXxIDFAvJRYWR7v+sDF0wlXDUvnHO2jB8KxXFFGI2xQlM6QGJnKbwyeUXPGa53drw/XDVpe4IeYZ8zyEBraoSu/0FfAqc/f+UcoWZnXrIe0x+04hP9BIxUQ5tWLS6u4vjUv5aZK7m9YvMc6gZL1S8pHJ7WGUM+2cJ2ScSAeXskF61dQHWSlyeEHxuUpTWVEaWi/H16CZJnaofX1ffUyf8+ibJQvEJbvo9bVMRCYfECNbmVW2wHZwbhzBII7F+JfLRZeg15RkIBU92Z6WFtoJyksjLArrlUigqU2F8yOz1ioSVz6A54p/X1vwPjfjZlgYBbnLrgXo1JcGBTtSwVyk1ObjaFm+Csd3tK7cuZWmTi2xLwtdwMBtwew2ZsExWbCvly5TnlMtt1v/dG4bM7fbFKtdqRAnUVEA37Ffrf2uoZqwDAnqEBV7u8q0rG0Urqkz6Mi8es0IaBEuWmIX4dwZjHWwPRaQ/x7totOW41MR4Ua3EsrqySgf0lnXRh0wPNKeoEMSphZ8+jEHk9mhZ1mfzZPPDKliS5/PEtr/WuRnXWuDTss6BkWxutyYXWR9+ItuT7tycubh4M9X8/nPaZyKb0NdX8q+AnigUETya9a1/VJB8n4Q+ddxgxSvUomolNPqNSAcuI2gRnpOJhvJydypnXfDJZggMNFRiuUgo=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

