apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgA0DrT4Kln38pxywkAWLFLS8qC49YWYtIH0J6HfTr2zEE/qOnFlsPGjuxrkIX7gLyKDbmUfuC0tfdJ1qf9frqpeHpPgxNpTxzeDuV9PUonYKsUzukuKEV2v3EF/LcaPWgvejwAOmY4QnSZPa4lxRfgoQJed8Si2Gu5Yfg19aws2HwYiOiRCjV/7Zpo3CUlbc0lHpn2xCeleKftpVgfo6SkxrZwo119hByAW55fJeyfOwkbL0cF3n7nb6oKS3/y3tpPFdWXSYDDciOtpibU/J5vBEfGckoQ8whbPIfZZZzBodXrL12tDhwrY38W4gvuI3yb2pXKbCEGIINumUWrpaPc5D1DYlc91MT1ZEqbiPJVSYm6qufNkEegKhAh73TBcx1GmPrC54lyLiJR9yuLtuKp3ordT5XWzw5V1D8cpxnfC+zEzcWY2/qXNcXErS9Z7B2iQYsJzm9RThCMd2mPmWsX79iJ3TU5bZrfM4q/KUE4buyYAW0NFKUFRVCjBWYUVWDo8na1wS1+PQGDy2f+689g1fw7tO+OyM4/6c74oVQwuJhrrvgLZFndioRZiHSh3izzGshZTAHaT8fBspS7RzodNc2MpvEv3q6RYYniStqwb20e4v9wr6fcVnsV6RxxtTT4TZV11ecT/UsTM7X/ii8RsNme8gb6Ug9xSMzkkr3AyI6qYMzLb3hGgSnEjkgioS317WzGxoD6BHyiekkqQSqJENT9OL/gAL6Y=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

