apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: kube-system
spec:
  encryptedData:
    gandi-api-key: AgAQihF4zAS46n2Q92bZCuCVQBGhoImtNchVAjLL1sPbIVgts90LFcTO9RPl5jacqATUcJN2qYB/C4al3lspxelGRYJa9Nccha8PwDcojb+6EmnUYn6ddfSpJo52d2n15tyWzrk3hHKnkU1fecQl+HqGoPfZ1R38sIkhi53KMjer5wNJkRaPlZDDkODDW/BXwtdr6bztJ5IsMwEnVAjJ27tBuVyP9WIHh3hbVjdgs/57FKST1rAjNt5pvk1kr2Syu9yfoghmfjJmXqAutTRCD3BN+S5aUafAh+q6qLGW0nUDzDUyPnvi/NJ+LxP1ifk1oB2CfEhGFflZEBKKPFaRpm8ivQD3ZFsNjficRDF9CCIyYW780Ph/T4lH+UgKSiEd+TvysD9j43Jy/1SsIfqKdX3YJ+Ube8ht5ANVX+F4MZDRxzXah55xUI5HmpNZqOeq5TVDW1oYv8eFM4x0R2bnOKBtc72V6lmpd2HyryDhY22GmvOJ0fzz/UvICpvMws6euahOD7Y4umHqc9/sUCt50iwCx9gmbhApknYHYerxmuAzys2eMDmH/SDTmHxdd7PHVBo7ZXlEz9NMcMJ5/5BxAb6JmGbckQLSyTv4ivABUtFEsKLg8ElTfsd2qPMDNz+f3YKFSJjHmIIeABEfUcA1AEtJEnU67QlDTjdR2kfCh2AffrsCEKmJ4+x1UXvVebeU+igWHKOdPEMqT9MXmubWNeTTwmrGXwe8fa0=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: kube-system

