helmOperator:
  create: false
git:
  url: "git@github.com:andreaseger/k3s-gitops-arm.git"
  branch: customize
  path: deployments
  pollInterval: "5m"
  # readonly: true
image:
  repository: raspbernetes/flux
  tag: 1.20.2
registry:
  rps: 5
  burst: 5
memcached:
  enabled: true
  resources:
    # If you do want to specify resource limits, uncomment the following and adjust values
    limits:
      cpu: 100m
      memory: 628Mi
syncGarbageCollection:
  enabled: true
  dry: false
# # Enabled once prometheus-operator is installed
# prometheus:
#   enabled: true
#   serviceMonitor:
#     create: false
#     interval: 30s
#     scrapeTimeout: 10s
#     namespace: flux
