apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCPXmilFUC806jmfEdNH+loXEIs+f5N1GHfcFXK0JEDiGyJGKr/QXliyA8froEK38npr/sHrz6bfvskcBi3oG19d49PRXARDXqtvMjRztT1r9b5AYQVucqUGpdibL5P4CXNE5UAv0Wfi7g7cNQxI1TPD5ZV9WpLbvQgmpXRVmh1cBXrkwzM4i5Wh4N9IUjSm1BezHAoxl0m7TakmkSc4qGh3m8r9l69P4B+IrytvUBrSadBSZoDLKsAVWJ5E8SKyU5Yv+7tn3i1mcU1lsPcpnp7QtLS8Cm1bGD6D8CxAqTYnFASjVAmVsgkggHeHjIG+TdmMCfisiUZDnjQr+8722IMPzVq6h2qBY+A2GOws/kRHI/94HanAJ+/5ab/XR4J8uOTcd8DCYZF+UmEfeOLQsx1TRoGVfREEdaxSFY61z0y5pYZU/nhsegYLYaIeQo7301INc0oaTH22wS69yqKCTI2HcrAA66O2a0bHpYIseXvuvFKAg6wY2zEMx8pjnwqKeqXF4GN8ofC6RovWZ1DwjbltLxomEM4lea7zuBKBASzaOya7IolZJW0rUg4uwOCfVgZWLjCtMBZ0kjGgpGn7oRBQZe/yHAV6lQDhI16sqYrXeV1KjBqZBJTP/EJV/9MnIfdB4/tD1hNSfh3H8bXYzAWPihO12wKIWpT9KTPXw3q6rR1c+CkwNqQrlWEervvtlPAvux4mJOgj/T+z88GdBXtwuGR7gShfz/QIcc4adAdqp1IRuiLcBpUMYjclBMFLJzQIDI6fR7i5+N0TRJNacm5eYnQT31JBpa5tjJmMk+MfoHxO6ZEAo7rs/uHHhBbI9sFWcMu4j/x0LTsWaDYjkqOjIrWbEKL5bKNGKBfvNcEwrVMUbqZPs2Lv2+5W/G67oWRvoqCzA8coLbIRLKMmUfaAAqYAmVRMpKuZXZeTjV4sy4kbA4ucOS+IrMEBPuZ/aNMkQw3muCrIYZFV890lbud4jWo6csM7Oa3gpa8CtVzEXXNOn/hJ/4L/MtOgXouR3e2kaCd93DMr4lt5DOYOKDBBy5suDZzVajPXmMPHliF8B9XqxMRq4ElkoZgfpVvoLkNyQF9ww8Zhjsn2w6P9F/smcnXFLaCmzomZEcEDfnQ+ELAz/6LUa3ElbkmsrSYJVcfrBIpVlDFzUG8Ods0xbrTkuttbRXmqf3IE6DTm6PQceKeXjahOnivgijJwk2+vZ+5c9ngwytKEgoThz7SZbr1X1cAqKJIK/eFo4cq8jzoQkTYRKNlBp0d/ADryjqVJbS2aUS2Veny76K5rgJ6f6tR1WQ8vzVj+xiOyT4xf2ragPDwzpRU6n4qgfaJ9SWdyz4=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

