apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBE/xt3+3tsO6aFwGHbt+utBHKDqWka/xl6wz15Twc9H9MxP2BGTeQlVTT8MQ9UUt5RZG8yMeMwo16jmLYmn6uD9rSAJhw619Ky1A2p3R1YUC64OSt0vuxBiNJQLW4Fp3o+dxdWaYWLZTW4lXhBwcyORZ0q0t48S2rVWYYDGklpzCCtHXICIUL6fWVVmNnAS06hG+z8c16I4spxYGySM3U7rLwPVsikC/cUMBU54R7RiWzSMunKG8kCJJ393bIqV08vAOyJ2EiGfAlHWLNxZU+lN4H+PM3wdU8cb8Ix+gD0vwgQkbVco/PhlrPEk/G7nhx+xATbR5ykfEks4mY4tPsnjf/t1wIR0QelzBV3guLW9zvWrvw3WB3DA7xN1f1RdMacnCsmMOmVDdFAerWt8Z5RImRSGpy3kEakc84CQtuA27dYlZ9yyJsziQEjdDg/l2iU9yMH3qUKNmlQdDnGUgYfMnAKQJCGzEytdNk6LihBRL+kpEghUkOSe3l1QHjlBOcgaHYmYK7z/R0rGwLorbtLmtXxsVml0ajqNuKAunP9b1Cv9Ns24JObtQiiDTbsNU7Y+EC7zKMbj9n+d4frNB8O8VhTuDnHePQN/7p9ubjMPyclyq13bAnj0UtJbbDCRid3E3l1cS4X/z5pXuQcj7PU4aNPEE3AXLo5Ceifh3ur3+BAXHo0VA0IwKMkmyXOFtozePu0tvC2/r60TMStuJu7Q3Ju5xDZ/D46tT38zXvuCTrx/o4dTl+I0D5MpDF0s9kYSHu7FHL9PnBuWsl/jhK6PMMXlaL99ZlgfNVeyCfdrCttRIOYQkbMALGDhvaNueac7hRTeUP4+rO5LqBEwdTjxJOoOi1iKprne+mUtToklhzC7F1D4AKnOUYh5KS//Z/hWElmVUaddFbM6+lp0MzTOI7sFTaXTxi5A3i4i0bngxtsZebos6YxSJhb9jcck305JwMJf9iYNSR3kJke9y2onyV03KpZSKoC4K8HqDUzA8d0rMMj5ld27uV6WZnLhvClrAiVMRhCLVwPBr/l2YXri9w4gZsvHhjxFoC+tdKcozRPxegY7gNSR7t+ByngK6ZLMjA7B5+uAkpmIB+7u0op2OGs2CLZv0vt29CT6cOCd7qWOp72v27uWGScH9yhhkbwMSsos73PwnzXryQf7uLXgg9XvmXs24lgAPC5VyF1e5Fhhu9EbqWcbS5uyADtQiU5CrJpduoQXGQfvKsg4BiEipolB0iQcZQWxt7nYo+7q23/9a9erp47bmqhLAse1b6mqi1td8m/S1if7X3bgqHWzg7gwXQYAWD9UZwXeDPYbAmBOkbO07MgIN3vosJiCoroKp+KjJOlelXyEb19Bn9b32DX51bd0TXKIjfyCV0H
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

