apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCT6O+4/0WcuuZYLbKuJvqW2juf3wXJp2h+86Ir2Z3q1LBWqCWlzDjN9rMU5+v4cD5d2ONWAJY++oMo2owI1GiLz2KsZZjtyVMWLYpEqsTA7YUtG4AJt6WAy4wLktGwkNf3rmNIWyDkq/BVsOAIs1Su2swc5jA9Glp/xX+qmrTB1pXDqsIXitz9IXGCEyJ5SsJh3UKI1nmiv+3UpebTTEykQJxbcFN8QkxJxbhl/KCRrLSYf1xtlAKDpTAnHxUkAA1B4A7yrRlMdxxooX1G+2TcZiqj8GqkTSH6Yppa+3CnlJvnEKkQ4SLLfpJU6GR7u4X0Rz+WVLsD4xE68LPyeo15/cQljOHKzDXGJlG/YE7FFbiiCIvJMKwxFHFmkTQSwXnfNqQHs+Qw+LcG6VdCs0x4elk7B3lMf/VSQmrQKeEXs+NDrhuh5Png78d61Q4vYhhnJMA2X24GAvtmTFKWsZADRbSXyXs0BvLp3ReEg501EAPVKNOZAbcesRtBEbn0JSNIfzNu9zom3KBSsdGsw7q9WhD8isYvIN+lIvGgqSupobkDqSGbs1f2Q9kQo0Td4yM4FoSqGspd4+co87o4mIEu/EBByysQ2ndiQgtJAhVvR+WF6YT60c6orW6aWqyF9i+hHVRFTJ8LKm8JK26gLEsJ1R1ylFtaB+L/l3G5HgMk6B5V5yX3l6O0ksdMtwMMdigZIRDIsuS2L8PVcaxM20hafeK8P1KmB2T6mmfe5L+g3Abe5ZroMPmG+2AAQnkD7O3o6wgORuPKjeu505tXj82g1YVV6bWu6jPcL7DgHITKnRaAS2w3Aue+bJNxWLDFRvBhZals/Lr3/9/fdywFCV/qY/Eek2HUsrnqdiNNe56F1dxrcf5oS+jLcFUt0OrT4s5+ShgnFMnXd4YhhOXkw/Ns3jBaasJRoiCAaN4EVrpLo7grH3COXkGMX02RFE6viVOJCtt1YWLy8MJbCvyW2l6ZEixdYLZxd/cIOig1aX+FLKuDUggqQYtsYKV5C0GNJPB3Fn9nkFQx0tQEVKMl093fvwN+2FSE9v2a5YcueQQH0iJyM33uu0hOdfb/cE/oP4czPKZ5emuCv2e2ceFCFF24DvLMyetEMJa/E+zmzJCAiDOE4gopv23pPPC1FeKmeE7+ARrrTAQKsaH9k0jKKK9IzRDdv+furKlHaVQKfjiXs1B2+aKC51/Mph23Ld2YJ56VZy+84cXjyEk6x+QUkFnDQvojPeS1jXGU/tYJOXEen3o8jnvtVOshXMHXn4ReFIi9xhqs6397VS+CvFv5mavJKsQbfYpfiDi8Vnnv
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

