apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCI5xWJtE1AhfQ++uvU8eVGy7vpQgxNtNuxogf3WOPScP51VR2caObL/8VDjlPNo72FIO81DiztraPrsbHZxYBmqlHrA0TM9yPDrH0lGm4L8hAC9d3Gi3gHwEmmsUQElkbpK7EE/KU5Zgj03v7ObBdFg3q7kvDp3seSB8In4C7u3L7YAwSYTwW5NE5V5ejTMyvHNU5Ybg8PGipcIOxzoxVEOzBhei2GqSKB4bY+J1PiK6pO66Ux+fItxvJBrlfU1dum7wqDH88apxB4symsvNFzDpWk13Q8h61ytjjJ9c/22eZlK7gAP5oX7zsHIBwBzBcljeXFfUv7rf0OhcwyMDFaUzSyGbNUtbQnMnbi59wHYECQMv4h2B5rT0hqIjrlp6hT/pRQZIEZK41yDqDse+JGmaMhmz+Jwylob0golIWZuDLANaE2vjasIhSyofBo8FslYZrG1qi+MDPS6sgxHZXr36stJsHTe713kgi0HGaLsX3JaW9HAgXx+fv/casVhWEjTDGK3boT5r1tLzI84MJcwDwvWbD8UQqX2nqcDfw4SSsfFCdE0Paa8WsWKRZB2d9eI3r4mcKEpdxnX7iKJO4cC9Zn4Y5LpyJrYcJ4wcliGcpTfRNax8fZayi5ZScZt4kCyHA0Apy6j6rcjqqscjYptscgxsGFNzgJZTksxhm2uerUKvhQYuuHN6AtrgjPBLkAfXVv4RmxaDQqIzqyqztXzIObUsj+rt4rtPM5m25FAdxPqCERFFNNjVKCkqZM/jAQ4lUmibzGuooGeHBt3mO1LmI0pmLlvjvR6BSTqTBnJps80ql+lhIYBMt+lPqdo4czMGUdMxeLF18/xD+zSKlFFbzuK83ETKQ/scvCsjnBmZNbtDipS/50bRYZjPnp8xudpVDZd1nrfHCo7dfW8kboqIP8PE9JxB6lViWcul1SM4eKW7fMksXfO+YQtbshlHQIcO6rerldZgGL5+WFoksJPZLD5cYQId7bMkRHWDPs4N7wzlW/pNcT8BmLR/hds6ZAz2J54DztEle+oFNQT1NQyvRFFOFH0S3x9jnz+GNBxbBG9sr0ScehNvEuM53hrzB8JxJcOI6Y9HvAdOTxSIHhuEbHvT3i22MWAGYrfdOQZBUNNu8DWU8Fgeyny4yih12gzteheWD7gajxUKl9s5qTa/uUcalSOM2+om4tp0XGryjI/hyE5vS0YBK4CovsQ/lvDk7zGPy0GPBT/7mRxCBV4wGrGuYF7CcIMbcv2TuQLI9w3JYSpOk9PCePA3nYhepM9hs5jM7Ijk89NYY7IDg8KGsR86O8qmQBnUV0nD8NtpKlXX3QKljtuPrd9y/4l33Y/O049hoMSwNAAVGHJfoYzz34G2xrV2BEqmU=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

