apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBQI8ODNY1tyyDCir9JAM3od53KUJI2wf1Wg3+T/hcagscE5EJHJJiOQXHhFuu9vU0kjq6KMuWI825NLlaUHNcYkDjFPf40rZyqCmZFzRUgHuFLkpUjhahijA2KjxF6iMr9nJVqpkJ//VE2C84E6u6v/M88V6kc0hjnR/2QpnxkK9Jza4X2Vr18v/LhxWDBz5GvXtj1p9+rcipMaGiTu+QyjGgoO6wqh0oic6wi/eFy9yER4P1L6URhlX44y5DjeouO0Og3D2sUCe8BzDpyxFtyZGBlcRqx3ISDl/I3WWh1K+qE3bOYu98bVhEasrWwPL4sBnv8xjMlJbhe9BCyeJaT/oKiTpC02+Ne+eCRehZMT62+DgtSk82+Gew91E0zWbbAPB+I+TGhKUqbvgfWaC2ynMxideJrQbw2PcEeOcAf6kJeOanJppPEbD4qfbbwIh8YVGsmECo3b+xkdpvfhOhQYIhiroau3pnMP0WJ3WCaDz9vz6n1yPtov99jk0TG45KlDzJEjHf51xYx20Tojey9C97YWy2oZL2sBPFM6b8QD8lAidQCE5lt9Tl+oyqBKwrTJQA91vcFTq9CxFtvQsadIyg0g+wgUpYrmU42ttE9DABy/Sy0Vbr/Tn8ZVyfAQHqxoOTZZYaTfVzAE5+H+c7w68X24oi5YKqAvZS5cXyQGpiEhSUfElKu9R5/ei8nf8ydOygJhIh579tSIZzYDkN/i4vcopaVmkn6bJYh+7gODP7jKnNQwbFq5GA7MxQfFjF1F+4iMvVIieXTRpUMlxNJNr/gVA/x3L1nMM8FlvkL6upC2vGidwR4eRpRkRWIrVG13kahZbmXVlasCzCLdhR/Si8DC+9+EW2qKMaTpJAPBmONqcJQQjp5Ys/GJcbwqg6HwPNITOVBPJxoMwFhHMxgsf0R/7sNCbBTEnK+fU6rbafyRs7Q7SoutqUcYeKveFgwG9Wx9MyLgtlreK6SPob5sSgM8uafAYMb3bGTaY4JdsxydLEafS9XDFIkLu0E7OW9FSxf1exaM8Ee35c9se24ofZ+Z+GdXCP8q5J9yc6fH1LkLIdk5UqilPj6/l0rz/rqE5Vnzco0FSwze57p5yf8/9Z+nAVN0GpJ0mb4IaQhkjO87qWS3zFYSjouzX1fydqQ93QSkv+N6TqGqPZhEsGkPDVslZaTmcEZIb87iUSDxPVe4IW6mWr42DTJVK3I3uWjIIEcD4IUxJUxgjdjlMXAQsjnDs4vJBh/urnisKsV2P8iOHuhrbl7TuLTxHDRXiG+rxRbn2kYF40snMoUD3ifvfYwTFBfjNSvj6gLRC/LijzjDrDNb8RbAqRuofcxR0CiyBhDN59XUKwE7bIeXnRdNjMg7lfrDK0vd3O5m78i
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

