apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBKJTQ7VaEEULxm+CYWvaeR8jhS81jaHl2r9e9cFbX+AlTSRKhDgvICmNHP7AKZco3QPnaPh1ufBBfuN3uyccVRC9hxr+pbPc9re11bgzcCg84YKKjF8LldqsYXIQHzFhcKPE/105z7YoGN6GxVzFyhDyrFaqiXU20lpolrVTsCTCpMCrGTtN5eaKr0sifvNn2kDbp+/eBIlG8BYXqVqbimITp1TlyF1F/r+sZvjKVPAoAwJmLoL8Hx85kA4zaHFNcNIMH+oaw2IV4eiGK0n0F931O5Ncl9GFPCk+DIJVsbULlsabzhmFegKZ0lelJyD8XBUVsNH3pjHCcqBscGvNyPUR7L72Ii5PMkaHB9W5nimZw/DWSlx4RbfXr5hfWEMHZufWcD+QYTsHD3FbR4zNYmzCeXYE/FpZ6nt2gt2xOFIBGHkdsAsNQhuUAfAXXFRkLZRnvhoU5QkszvPPVvBfIDZpxxJ5T3D9eO9AO2K9ewe407i73dfEOW/3U9NcRu/a2cte61CKyzTdrO8yesRkJkWwlsRgPkj95fXyl7z5MG9xMCaFetQkMamT702FOHa+xSdY1YuBdbPmZYET6BEiYF21/3FtKteUPsPy4g5nkQC3R0Fsdny52gIe2hJaDxBdyI2wjzCOOZp9VgVfJO63dKU9wzWWTvlWTHXc/WFFblOLBwCtIMevmjE0uz1s96/NIU3wiLJ2/kVPDRV7JjMNpR8RynyeHYxoElMzAQvUOtZfkv0BExre5a0dOtnc5TqkGfc1WBOleoy2oKQXoWKP3uZIh1bd0EVLulRCyDYxFRqTgNLk3rgq1VbDvhxgfq9K9GcFSbvVV6HWE2BYJ4eq7rfEHa+j4Sdf5ICSWDFH9WFWIfgGt+fmxzgrBH04MFaqR5Etz6HCDdqvRJxreGf9jSDZJkV+lJgFcLb3Dm6RVtcW9IfUPNjmmnH9CR7hm2ADPj9luHRwQYtZLHXDomZx+cMhRiVvqP6wxFU8yYBcSrgnQCj0qCCEUWotS2fYXTdf9tq9hcEPaY/k29z5euq+eAQvgh7B4tbnrFquUIEfXlXxyZ0Adw+1ND5pTNE3QJIH58nY1Gk2O+3rilmQvB3YKJthbH9dTKmL/Y771fUUHmiRTIZuThl1+LnW2mwkTwn1d8Hq9ye908UXjCy4zF4iruXRl4XssZwfZBxdZmvs4D2Z+Rh/eWmF277u10bXZ7ERZDwkpFg+UrZA6viuKUSZH68EnfR+cFoiXaN/bHG3T+RwbTj4kSxv2mJXKqjMePJcbPZipmg3zlm7Sd+Z0sv74=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

