apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBh3eNfB7JGsknPDwvS5QsHUd0roL5mBmZA8sYvKEVgi1t9nQYV2SlfZAxWVWI/eqtRCq42cuP38005MKhptBXIvKRYGTjLLwbH9LztkpEc8gG7RUZ5FxQq/VMndfi2KSVNVBIdBIlYJXPTWY5VNCauCW+SaLkc+hhFWxeZ/HGySySUXo9QlkZTF3YwIeoEhQwBPlLlafEFLJ80wGHwr/TpnxoqLteKmaRK6slAr0H6haZo82TMKMOMhRveX8WN+k8n2B1pfvuzct/matPljQoilDC7B47j6gQ483ldlWYXTpzINFcRjEuUGdNdjDKUclJKPYa5pLglgXw5qFxBgUPbZWako2kCZbGdv+ty3WMe/6Lf5pCKXn+9nMeuA1gh5fJfiF7l1AV77cnow1PWLTfFd16cadg8I9Wk+bffY7NLGDUwehug+gE9Cngpx5Ax7jaTrfzaU8e/oT2GlwU7qybqpPecZ3Z7GBSsm2LDwOwqHJLHfpn+lKuxS4Iy+q43O1F/zYR4xH4LL0lg7tID26hIb9cH3VeSIyy6yQik6ytR/ygAIzOYFsarI2ZL7lztsgpW8uktfgsbEAw93OdHhrmuaxih+74qyX6+kQ3LZJmEw7A/2FBP/XxDtK8S5klNys91Pc2ZZERHFyAcAqsyZUHGRFrormsaw+Bk7+YAJu9lvqO/5r97N4V7ol+3lVXtckGYZuX1N3BXP7WsPInDAlW7HRHNsw4GKnNitrDA2l8QaZJ/JThTeXAGjVjboAp40KAjoN6puNX0WgA62s+Iq5bOEzMxAUGmuoRJI6OpZezbpF18BKXtWb1FEbRtHFnKqvXRFdsJD7JmdCxahz4bmqFPId+P+XQe8pLEqEUzW2+NZTU0+iY27nsKG6aVcfMEqC/TCfpJ7JbsKnnmYNubYzWXSY01h+8YGQhM1uExojvslQGst3l+Criou5TD0MuCIUfBcCZP/UTPWhGfJN9r1A/YRu6ptE9e1tR7dofVfBZ4Sz5dwZLPP5mGdfkF2Y3XsaxM+w8yarroja2wUrSRmko0IB6l3vQIeDNXXAbeASjCJbgk/RuA/Pgyy4cq/wLjtlnN6E1pyIvSJQ7ehCcMLocMo/39y0HrRV6qdzMw+Nm8PyFgO2+0DiJO7yKZQD5HdYsf6loHTohnThRLpNFhjvOhj3D7KKBoEgJCIr7SNKdKWDaNIy9QUVL+xoiCkR6/SQSUPrgOxKSFab2PZPSVHQ4zAmsKOjLKgKBOa9DqVWdMePJk4JANoeWJ7wLycAqsTQtHOpGwGVYKEFGIXI3NEFip2/UE9vc=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

