apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCTonzhh5FbaHO2LYgRkq6aKLXLmLjHzKBeiZA5sdX0ndOo7lbgxvkQPltroU7B61ybnBxbqf+u/3XwG1E5pd/GWvxzVcW6GO09g2XB1ZaR+hrv3vkP4RSo6J6YmBnyqJ3SESpsDyUE1kaxXCvRCZGjXCnlVm/Kh4p9eZPGUDlZ+JbL9j6q7ud/bBQheLP0qk5S4zTzvOWpvowsCbfQn13LMpr9tBArS4HwcAAk1WSMHMdVvU4JG5Mw6Ml1+0rd05XSZsnU8fRWI35ew9CrE5n5+eZRmFGNZz+mReDCBZ/BOSXKGmAwJ3CfxMr7mnutixux+osl93PaSBIQ8gat41JYHfD5G8UZ5FiX74lwh798tt7NYva06uiqSODU2eQAgdlASD+/yLQve0GWfjwxTf1TZ5g77w0hTJuLILveFUfuwDyYlujzjrZjRndcrZOj1DRexAARiV6pm7b39WmmN8hDQBRSaqQuK+MFM6qDky7bthhnWNIADY9CT9XdYXc8hU/C41kjYQrwsnvNuCGLST88xXRVNjqWsdhzaUK3+oOCrIpv6HGhVmlBIYV8gQA18xh5aME2B452ddXqlpX69rFxpoE4hEjgmjK++dxaaE+KkcOfZ7vSULXBwCN92W3ey8eed6DOPbFYBDytYMl8m/+NfetfCUbx+tyySEygsAIAZus4kks7bzCEY5CIWcHp2ujC8eY5QJS7Qvq3/9R5doIid8x5fAWFi/QvHXu1FFY966gCWKpLSJd7TgKXGp0uex/ZY8Y0+lhvAamlcYEvVMhIB1zeHOtZCSQ90eE5mWKiREu9cuhwtn8wCh0/eZ9ZqY5wkXkZFzS2FiYbXMJwLSkEYo2qrjThUrqrvkXelXoal4HQFbQyyc9HHHu2Epg8voMg8dNTsA+5JjWx+D+WlBhvorIg2F98WK1ZVagZN5XYcpw6tosPfHl8HNOqTysopmTxr1qzh0kroV14PPcJZfKcLdjKOmGIwllEX7jdnvfXTQLFyKi8oJxUJrXeVzGSSGrEZUX00GiTK+n9LVFbEsnKEPtWs/v1y1qoKzvcVal5aAHOomjWQF71QhKAqpB1R3vDqGIDPCNtn9UL5dLOv6Flz5ji2kCj3whM57wSsoL0qCcdzyXXYsT7tAf9t54FBEbdc0gW7r7F7low78CJLDIq7ANbmRGQ9pVfoW6pcalgjWllICkiiUac7QyffVCgnoS6OpfQ/vxVQ0dHodYWp/1yabJ4F1seoBnRt65vbu8tom7blMucf6m8YvhcfC7+OhnZSjnd9ywOBlRKJLSDhRBe3+Z585naFdQ0LrP2y1gHN/Gd2TflHRjXkc9fUst1lZ7+DDinBBlVnbKlb3G2qKxHIUjPUIDPcQQfwK6Qryj1
  template:
    metadata:
      creationTimestamp: null
      name: pihole-helm-values
      namespace: default

