apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secret
  namespace: default
spec:
  encryptedData:
    HASS_TOKEN: AgCHcwmlHZqUj8N8gwn2IUfs751iSQeRc5eBkB7e+JbGle8Yr54QkfmV9LQYOwaM9jI8EiVoFdfYYpeeoMtyd/bsxdH0MUhUL7GjEJ0WprtwJlm9qn/pkmA9KA2JsXuTIZkNY556ffFWcyKUcRjMtA/niXKckpx/cd0Iv+5Rcl4J7ttG4q557YWrpBZ9CCZrLWf6gxI/QowJM8jtX09GSBXd+zT5kmlT9sshrcGLAYRyn+xuaPwuUgqt5hbotmm/3xbL0tVMNx32yANW1/B3XP7GWCfESDTdnGn0dGQWQ7oCDiH8WFeQWWIc/XEdoEU99GWpEJPnJOvdYZGZ1jUMNT9aCBiUoB9ZYuSAmzy4Y9xh9t54cpYlSSeIR/1fkcOEYQSFj6EwSc3oXgMTQ0b2mQ/esr3DK6u3Zyr2cOF1HGRjfjQPQhHoyvs/Dh7pnUeAOk2uHCxipxeB8z8i8LFwtzVMoi5b5jjcp/pJWWJgyEcnQSkr+PqJ72nwCgwOzHKQ9geJmTUbHXApXu0ZKTXe3fi9KRVkHh2td0ikhDvE4WBMNX8m+UxlFAN4JA2py4pWMx1Z624ZDLOe2+9d13o4o1ajp1lEcaOXgDhJfRCDap+tQLlrd59smGeHIHTf41xQ5a3cAV7UOmzzvMeaESPqBoXE0WzDfcu3QUZjUxzuq9yNykzQa5HX2fXBikjsK27Wb0cmV/fkDgNaiXXMahEa2vaOQtj8BUh38yaR4TdbNlPsnfw/LZGHQl9jBe7cKxLX21J+wtVgQaNAofOW5E337lerP4eqYOUNkfM3GrzQOsg1SVSRCRiVmKTzlV+dFkKWiv1m3p/MJRaijnDEDUP5s3kJvQPu3x48ZVI/TejmpoMlDoejbFG100/4zz0KF13uyGUACTmofH7Yr5Bla//XFFTPhP0C732iPorfPt2EkXA/8dIko4tVS7E=
  template:
    metadata:
      creationTimestamp: null
      name: traefik-secret
      namespace: default

