apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stadthallenbad-counter
  name: stadthallenbad-counter
spec:
  replicas: 0
  selector:
    matchLabels:
      app: stadthallenbad-counter
  template:
    metadata:
      labels:
        app: stadthallenbad-counter
    spec:
      containers:
      - name: stadthallenbad-counter
        image: ghcr.io/andreaseger/stadthallenbad_counter:main
        imagePullPolicy: IfNotPresent
        env:
          - name: HASS_TOKEN
            valueFrom:
              secretKeyRef:
                name: counter-secret
                key: HASS_TOKEN
          - name: REFRESH_SECONDS
            value: "30"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 35m
            memory: 50Mi
        volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/holidays.json
            subPath: holidays.json
      volumes:
        - name: config-volume
          configMap:
            name: counter-holidays
      imagePullSecrets:
        - name: ghcr-pull-secret
        
