apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbhydra2-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCl1xt/I+EJI0Es6MhcRmvkmbk9/ui7nVg0dmXRQuv5tSWi8FL2F4RpHMMr12cGu43B9pKYdQKDz3bK8uwftos2oMERIyMEiI5xU30WYv++664+04gwFY2wPM1YniUP0v1yPJM5C3dsJik58GUiHxO5KKHoOHuhgSoZIwwDeVIKzA1YEes95ZkKJh4RIo+inDIUKPy3WSwWVOnTwLzUg1yeR2FUJ0dtI6PtJcfEQJXXJB+VTXymo/1gvI9Xb/AxRBpTvxJa6pjAqQG2utMXPp90DGKrYMrc2OZr7C9IrZ8QaulUtS/jowysdmdKPTE3cD5DMpH1ZMj3iEAoSfC1ruR/4vHxxKRvXxQzxbvIA+4v+/aDH6pATmTIQwjIBaNHQLdxaOSHDQYe1X2EgwcPbCZACnN+QoB/ph/5eYsagXLa27CkMY6IV0PpGDVnKMyfQmyOaxZpOaPlAzqqwPNcZlTdnZGzKHsMDoFLl2I/fcToPexHEhrPjt7/MzcC4jNEMd4FCLMjlk8mef2R5plIIr1NpSESgTj2pNE/kiOFSZXBcf6pQJxu/cW/HjmOkp7TSa4v6lFKpda+4zrwhOZ0Ae+RUSpfZvMMJ1DJTsnyC4XvHbb/X0OWNF9E7Qwfud5jAlxCra7h/6V7EnVpmCorVlOoEfIhcgWVSYf6elx2c4LlqvammazgNmBuly3BJ/PXkr5PswH2Rc+uHu58bnGwvBxidPZTsIYQzohy8/xLKPDmBCKwdFPEtahDEfpnJ+Hq1OAYHL/TEUtQkY2QULEm6Fi5sw==
  template:
    metadata:
      creationTimestamp: null
      name: nzbhydra2-helm-values
      namespace: default

