apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbhydra2-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCanD1Ii/iMmUHuZJaxOdRHc1ZaUyM0WTXYg4QNZl/UVVqZYlUMx52bZkgk7n0mIHs/p0GGjTQgtEKs6b383Tm8qSWVS+qMAlDgVf0oUTmhggwpXQUYmXfxmPf5IwU9BGsteFKj+nhjGHl5qTwTZDbWFCFKN1RewcnbY+MS9Wo9H5vfvewstYCcSsxYvJm9JOs8uGNqcmhBZdHSiFizDfZIlAEYLBD0cvh4DjJBbOmbdaGi+qn/W6+JQ5Z9kQgMZDPALOgFMJsTLbQszCAIe7A5pjK8oMRfNAd2CaUzO7fR2rzS+0Zxy6uirUbwC2vrX+ZriHX2VxxsVAuGzx/73EuMA9Ys91xQrKDSj/2tK6Xd2K7OzFGMBXDBOeZZq4BTNUfDdkc3LzCkgJVoZX0NdpgE+nLNOEFXBqFlxZf9AqXlI0Aic5B5FJ5fmbK2qn7Fk64/uR+Rh6t3KVsNKOz5lgItY02y9dWktA10okYahZVASdwlYqPjdjhQZI/HBmSzE7KWApzckkilj7qxfuSZqrgXXNgNxw2eaPIYJVbZ4N87XzvzudaXd9FHdN9fC1ZmTX2xsRwwgvH4FnduiDS5HqIlkMlHGI4wt0B17uEOkMy2hLhZXEjyGKwmf2HYvhWw+oiSHk9NtBThFzWHqV8YAHiM/hpqIDRuJ9NVe4O3b4ogOh9/YSOhKIEiqFBzkt27noapDEURiIcUbx05EGwVT/gx4E0ZPejVBIt3xcX07DB4UVco1kCY586Z+MOaRz30TKB5bUIywOTIwuey3Dri6nZ0BQ==
  template:
    metadata:
      creationTimestamp: null
      name: nzbhydra2-helm-values
      namespace: default

