apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbhydra2-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBhHaimPyPSh7zvTR0Dh6IFleIH3ZPyh9+APGzjRB7NFqj31sEBX7XT662JEGlDvFCzglTjvaA6Bokzlbdfc0hAunIdnDmGA2RIIQsT0JS4YsJXYFsLA2Y1LTpFk/5CIV/wBZCbmHmQliN3oFMBCNefAkDVQPk1HOxVPWW1LlRDhyExVjqvSskviu0XTS+IWtbU5GjNRn6P53pfo5QuWvNv0ffRj/n+3WD+Q0LCllQiI8PG9rSS669OHorSc98WLEUumtHi/80LZYuYR3yC1r4CImDiwA2e92UtxK/ONabjykLT6OXnfFSp118VG481Kss8LBvKNdZAysA0aAUyHgUD0Vev/MLyBNxO7E3tnCQ6ToVSpPS85QS1dU5KfK2iVcK3wT/Tda+THM4NsTMeQvrtaeA8vneMflLKDhDoP40Eim1aIPjq+f9VVCAuNrQ6GlTMWBuMAyelO95XeCqGDQvt+KBUQnwfD3IHox7yG7t7yoB4Zpnxr46dviGu5jHZWGW30fr2hmjR0B7AdRc2SJxnXcKluGLoq466EwEPs9gelQ1vBNxkV/xcFWBv+fSu7lcPN0LBudAi3j4GbOuiSIWSvSZd2fTGcW2m2v3kcmJau6UjVUEqkTuGIG/C2mwt+27w7AN6Z+1sPHRAtGVKE0e04KyXEhHvN8w4exZeKFTR9rguzTZncFTHuqMOpm9+3skgbeeL4a9bgfWU75QCjmZInFETmYoyTjU/cK2o2UcbuqK2XrMjAxmHzSnewxxJcw3v9A9CWilaGQaqYdHJO1uCEOpQOPrgngUYdr3f2KyZuWY8owIEYHAnMx3VF85rqH6FK6Y7pCi6Iw/qAq1Hzan6DvOS/BwcSRR80Spi+DPME2i9gYOqcZMKM4B14FCcQQ9FcoO1tOT6d+5B2NKNVpLiH73ViZmPhahY9yO1saqw7uR9/I+cT8IwlI4ScWtHrzA2loitJf4g040+SZlpIrkeu9FsC0WfWsZDywDSBI1mBZStXGbs2ldqxbMSHfC+XlcDkeLf+Udt8Q==
  template:
    metadata:
      creationTimestamp: null
      name: nzbhydra2-helm-values
      namespace: default

