---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbhydra2
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbhydra2
  helmVersion: v3
  rollback:
    enable: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbhydra2
    version: 3.0.1
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    timezone: "Europe/Vienna"
    puid: 1000
    pgid: 1000
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 1Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 25m
      limits:
        memory: 768Mi
  valueFileSecrets:
  - name: "nzbhydra2-helm-values"