apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  chart: kured
  targetNamespace: kube-system
  repo: https://kubernetes-charts.storage.googleapis.com/
  version: 1.5.0
  valuesContent: |
    image:
      repository: raspbernetes/kured
      tag: 1.3.0
