apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB/9bYaEvHHs5VRz62zy6Fo0GPCee7+8pONPxidArPeyLPb/1+FqdZXqAAfcnLL9MmKzOAO7o7UbHztgGkv2P4zwDJ/dAYFQJoTxH/8H86wRRXgMb44I/HVH8BxO1EGO04fQsorsyZjzaxh7x7TcJQv6YQbSsh1zd+oXPcCAdJYjRZOTosqxjSrNsNsmrkhDVuiJYAIkOOz2b0wFstRMYLxM/CE7bFqvN4TgqofWxEOolmMw+ysNga1pTllWjVXUTce7zbuM1jiDAnEotk6hvfsNbwI3xGHD5Q1ZyHYpyeG1eiW9/hKbE1EWlQ1ysdGkik8ddU56HDtGva6m9a5Tg79jXwvwgGuKtWs6qLhO7v7U7PFQTKvSBRKEgWzNKBhahA5T3/JACBX4j1PIBBzAJZV0f+ST4bNH9v5Bt4lbErRLHXJRS9QzPEqO/cW5iI9o/ywLQlQhLgPsxH3i6OlPX2g5cM+Jp71vbpbZZ0qy2O/S4l3jLkB08SibRyuHa5xEqcZgpiP0XHNCkZ0lWYLpkzbuugWd1t4fWC+cI1Ez9DW2r2LPDD/aQJWW9GVxRTsVARC2P5LTMZNyxW1Nj3CUCVGIUiFDThTyFQAxvFJuiNsRhQfjXWLUpuCj5rYymIndi11ltm0W0tNrADPU77nLRZQSU5k8ZNnk0crMG9gy6psw8PTdeEAIVVgA32mtxrQ7epiAZTktjWnT0fxL1bx+n3fAXRSI8+lNf5oICHdCaJ+u3GT16d1oP8VIO1xQATnGFUDDdu/L5RQA4z8uBXcJlGQbJ/6HZFvNFZtIE1cv/ijg3EOgZOHmUiOBoNUK+Tp9//RcEkb/T1a+wzBWNAx2QaUw3Nt7H+4Q8be5g6/TDcryOFl1WzzK4q9WaNUYfEyn/mm6Ibz04xDqIaMwMB6dZy5pogrRaoJPXxeNjMr5/OSB9UlfDUrFO2rP4MhoifyX0sgh1gZvs+Eow0aZ4mla7KOgYa8vabc71kadRwmtxY9uJVm785a3MVAvJLnnxEKgHIiEniLZ50g40b6VR6DIm4JKfgy6NQ0FZpOT1iDWv8YtKFWzkbuqHat2jv2WLjQ35Jm8C5l3epir+y9ZfIHcQdZ+2Cbwg06GlAcLghO2i9q+prAYGZaNNM0OqB60XEijvrG6BmqFVPmJQQNrJX1gOumGnOKzyUIWbZXPPgwhqY+Mu6/4c3+llsBgwR3gD/okYIC+7Ay/WY2WY6WTPdTfXkbw4PR/DdEZXIDBsfZvg15jjltfrihYlweNWS5Um4y4Un0wTtEEbJlkl2vQOL5KIlCcZTK7WkVRNUI7en/tEHOihLAXUjG1LnRdfQ5WhY+SgT8EkQtzvm+kawt6PCtX0/8nCAysxHJaVGD5Zs+TGOcoarMb3F5R/fsjSsIQlNLwdZg68DkrpGqfXdCVQ==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

