apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgATlP2TKybbw9fASIeJxgHPSqrUFGjMzO+h0UQ/jnSYcjAyRny9NEkb6et5vM8elysH8Uz/BE/kpaIItf1gve95jKM4jZLDxWYcQ9UxyxuwyJj2cPsTVNw33IYr3Tx8DoKyIK1BYBLNPVD2P6UWuMEhwsnhO6YREoOVrD5EYLeYUlAi3ZlTvGuZs59XBhdxQmAkHoQ0mMK9avCcrQ4ofb9bVn9xLsQvtEHz+D7/O7JqMIFQDiWhW+AgdrwWdLwpQcVvu0B/9mE5i0fXv29iU1Lp1Tmk8NhYKNzvQ8b7aQpiMtxDQbwgwnyDXpZWcE9tDtrkPQY9D1lBxzgBlu7wLvFW7NyLRLBlaybzakp8awiSF6wPGpWzP2BAFbjzd395rDx8is+szKqaDQh4Y9fBkxJph1Y7FnR7bnIIdJvLGMW/aFRJmoc/smFGoN6HOH+ON05WlMX/Afq1/y0XucI4E8vA2slQTqggGhnKjN+Ht6L7TnsHocsm3CB+Oj0NdPT93WKnFM4Is/B6+36opZR8R9gXQZe59UfBJZmpRLTLFgaoS4eguz5bZ4mXi/FvaZoEF9r0DVctXYEbILawEpYL0SwxlWqAe/gNL/2MAgKx2diPJ/vWdzVXFqnpekgHVDzq3+dTgbLuApAENfOO0iN8+yBAUDfCGFIdrIU1SWHrYSmNT5FTQXL+guSt3gyLjRU8hZc4SApim3NaXMTht17c2gXRC/iH0YJdINL3iC6Ecmma96UFW2tqvjZkZ3pkENBs2aC50EPIUJGOh7wPm8424txONIt0xWi/YIpmoBQ6hM9hq6WYPmrOVP0nT0D1WhvvuRM6Bn1eHSNFJ8po3q7yJEiKVyhezi0hgvikvXZSMvY4PPOBH/BBpsB83G9tD5SFFhV1U7EM96FwDNh7T+aLewSowPieeN2uoyJUS6u6tPSwuiMO3tkvAFM6299bJxIW5Cf3SOwfGfRKQC+08OEXbaOwezzTGHpcV6ZKhogP8E34KOSZZDQbZT97X8yKzq5agvsILZ6BCpsO70LkPbH9WFYRgvRAhCA8GeRSRwfQFSwXJC+NRoJPMfTEPTwl7tsaS6KT+/0iUHvtghBsdMBifY2WRXPLp/1B84ih63XRjVmpTL9aGqclvPxaWl4RsmOPK+djWaeplJRPZacVe8iUwxsNC4diUYHiw3BQ7eV5NyJSdBesolnRaz13Q8x2EJ3ZYfnesUM4gG8CPP9OKz+kZDr2XhUnEpL3wRYtsCjtXhQvab02CuEkmxALue9a2MitXCjOUUxfbBC2zz+lHN28/Ff7cqVJ5pQRGe15Ys5jnCRDf5EWPd2p1SwsSVZWnFih77KXhdS5dXujwYLibQyeBZbVK2ngHxAraiRr8wzoaC9H8eLre9i3TDhpyeqVO08EgpDMecw1k1VK
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

