apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAyKP8K7gIDok1F33qlTsiSHjCdAErRhrwS4eC7sKoPBwB4m+TqlJYlAq687+kkgagIe1NE7XW6cbAy0Ue56sngNF7yIAvOk/jGe6iCGMHUZ2zoF7zqTA22zEEOiBLJUCyQXhaTP0d2aDL0hKyuQa05lWBHaZQ+Ji1d7wlLPxkEzBSEdbAPTVXeLG5+UeVrnw2yw1of7C8YUKYBMAu7Qiv3ZzRMKWp+nEG/X9JEImvt1JAgj1Xe+2Adl5ajIpT1i9qDGh7iaXiYBVdXV50Kpc/PYKwNAQJdcgvqgUBT/D5P7Zovynj4HTIiqkI6xVYYyTR8eujRMAECIA1HEmPm0olRPQCWAoby3oA2SchLRfmr2JorWpKFQUdKT5GAv1JnXy1sszBekL2stiXMhCyzG1jq/RizJzlgKlxqih0AvPWSSaQWXQJf1FfpODL6K0P8upqeB86s668B4XHdmgJ3BFLgJmdlRsEIfL2vTUU88sSNRwiwt9mOmNB4+G2ec+K4LD+esTe3tgr7MlTEicgt+p276yfGcpvhKDAw2ikIdOBfy7cma4L34B6Y39EQM8NotIBbSNe8r2Me71NXucosYdFYPIu9TV8Q/EA62yaQMIfjS0KtAlSaE8ouBfQHov+al6pSjbCQjQjlv1Sc/lM43zvd1aDb96W8GsTUe4R6eNwCRRa60S75G2au8kwfsDR0BR+kIvphS7iAw9xQ9RnguR7k4C6mcheXQQystbOVencyZ7ZRbCAt/dRzUeXKq3MWWJTWh/D9+79WEvFTvbqeUGfgUP1ElmZvxAC7ymq2ApA4
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

