apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBuvG2PPX9ekxnRky8ESBAkljPdNKqfAENvP5n99xX32k8jaT0VVM2JUelffeFwjxDoSqxZhAlPPpk+vjGQRzmYrikm/h2acJyYspGH3+k+XtYs7rhJo756oK6nayrgDRFhIhPGYdr3/MBs+FfHiCLPvVaiaFHqc1oEs2rXmTNr4zxrVPpZaJKEdbRECEcRyzISmeXF6vBQxy4ZbjZv2jIp4BMju/81UGvHN01vVlPWO1u6OdItm9G2dDPIeREWMlqH5uiQZ62kOjydEktp9lZRelWt2ApoFkw1jW+jsaZmoZ4MxMcwuQ4kW71JjxC1T/Nul75EXYxnB3kLsczRMHk0JOy7U/7SpykI2HEpxjB0k2B2TvfB5ByBdw4NbP3iGtYVVLnNNWNZPsD9Qh6fWw3WN7PC+MLijgQpMvopVQLYbjJnAljsBZXDJQ3fDkdnAJgy17xJpNbazDjV9a6YP2Opy+DGABuD2k1+8KyBGbxSsbpQLb8yo5iWnVq6pitK3Ky12o7tn6MKEXOVA7N8w33oCLli695cUPgykLcMosTIfPSUL/IQRZCme3PDYCVQhuy+tEoju80yTuXaptDWHeOoeslzVoTw5Wd+kFTwkTI6/izEqBNtiTz/jC9ybBe4keUPA2TAh5fJ6nKX1+IdHqEYF2/xaSAqPyzHULBanfza1jqVTCHT+DBAPImixs/Xa1n6olXC1M7Wik0q9cK3fa3uVGYwpNKbC/p2oTt7iComPbLmu7ZSLQXCjE5CgbQIOw7TD+CxyIq7BmLWruA6Kg7tR+wbwnqOSvF4jggFF6AkKKlNwh+YeUO9Ru3k+osvLeouFDaNtytnhuLv8G+QIvzxYux+v/Z9exDIgT5QH9QL1YRgfB4Jc2XBXNmxLVoJVH95OG23o5QqvcGStyH6swDJ4VqGvt+u+yaN333aPgwgDEEX48gGvuorsbM6GcRcVVzDvzjIsNX7Yhhb/6hg11ivWi7GtjwNzhBdgsfrbvpIOf9Q7EHcMnKzQk4byVpcpoaQv+vCfPvf/xvsVup0gDb0Af99hCxQJUejY61cWv096xu09I8eWci7buCnucuqr30zgI1gc9XLSsYdZFOiSDb4U4uqm6C7kLXXMkJqlSflW4sDBhxInbKnUbdFpUUBM/t1VQTlvKz44SzXgJqg7XYLofc/tOlP187rQOspkGWDSegzVW6cxFSCCls/GgzB8O1HhhNp3S16Z3V/q2/wiML/OYSyrAkvBXkOeDaBFvh3rBqYmo54LsRjsZrAu5+LavMDLADxKqQT04wIp02ouOYQ6NLPIpyOBGXdUAu3ZtKTjRegW57XoSm6Opszew8OcNNSkAh740yz2LT8EnJwMA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

