apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCM5ffNww1rKPaE4Ov+5i7Fnkhq1vHa1AGJrykaR21k1fDDV4Ces/DZdIzF4cq1zzFwBsaH2udApDkJ7xUfufi7gMNdfpNBzb8OR98Di37XcEsUwdHpgRQ0K1AAVC4IpYCczdj40laG2A2/uiAEl3VcJUYypH+bWEzLx17RNONIYYx9zBnEXuo29sAxVaAy0IAyjK7eQoTZyJplSiXybxsSUGxaCrdEHix1dkcUPDQKeS32++1j+FKsus80VZ/5fVyHF8U8C2SDwimcDARTLC2pUgpYWsr6WfHJQvKdZEUnGelUISbs7fgRCpBEkCABFr1fZkns0uf+rB+zKcv2XPHS+Xbb6Bc9H7Rz+PrZaDa0gFoBXifVUaVb+9/03NqjXRHmCNTyqO2z1CdSd2HpN+36V332fMjljJc+7jha/EKsY61C/q6xfckbNeOv+qiPWpYatCo8cnAs7k8OUbzfdfiWXz8DX1l3sbcEdFZGNDb3Muh2VOlZ8YVk+OrNRjrLtlIdEZLNdiBpW65YsSWovohp96AjbsVd0CvwOwpCjnxJ7nEiw90w/nP9ctMsyFL5a96CWyrVdcYVUllzk0wGtgrfvlGWvZrWA3vgYhyiBhX/hGHE6o+/II0ot5Q1NaRqUjV2S5bu02tAU4Yhwl2elUW3RNRLCpB/UetCA2Xg4bjxiU1SpAaudZycWFs8zDgHzt0I+oF4OIeMpi7KwiElU8bgQK2/bwPgqBQ+TvQXgkCh0kjQSyG9uCpFnKM1ujOue0u7iwA1F4j18qcyQw==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

