apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAdpopTu4I6/FNhOSkbzZQfMKIZMVQ86plYd+MN3ImoVru+j1nNMXQwaplHGRuSx47WfXiEgCG+FvDkWy0kuQ4iCPwJ22L+xF0A0Pr2TEZhkrVMImKMh4GfL0ZfixEPi7g4fOHtNwfr5ksrp4978MQ4jlYLyklsF+KulOCAhF55svIezC3hA1MQjSlR4ubCaxdcqqB3fj0jaf4GuvsiSLWTKzkGNxIiAEqWGObL8giW7pKt9VcldAI+hX05WxRN3X4hHzzTXe6fBzUrn4U4vuJazHd3kPkM1PHlant8hSc3JfxEs0JvwqDpRAraXJ3c/De/z66FAGSNgfdK8ocEmMe0fc3aQk6Move1DIgy+uvSS7OuR4Wuag8iqopmzgmHFxPmxHUFz731iV56u8XUOXxiQizdoh7bCcL0r18nVuL0HhUKSH/fomIDNrONLhhvuujoQY9VGi1Uyt5O0GJQOfaDATk/oGfaT9J4YGGFNAg70btsFQVmyeN2E36agvlwZ+BX/iCLHYtCdJRfM7cNqcAqxd7WtJLinoZu9asjdLpmNCt9SQDvrevjFDUcRgL0I4gPl+Ik1WQxJ2R2xirjXpc7sl70qSnkI1XCmhEUpAMeGW9Fy8N5P7KVQOitcK/Z61DckcTmgNCQaqfdv4HUdh3WIqo5m1GLgWn9CtvM/td7lblHoNt+tS/vGqwuulEQpJ/WfVVV6yC6GBkWuZYSbKlOpUXMX38v8gwhMp4o3qPTXS8pTRYt176RzhyH1VZ5piXvPAlOm2DtNwwRNg==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

