apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgA/QfvSfaVCsjTOToip03fOkqkzYXLdYHypz4J0Psi0O0+mPiumq0RV4vfoahAFtGehAB3sr4FDBQ4SVECYXNI+9c7qoUehFXPYeXB4rEX6M/oV++GzMlX9paYpuWILucG31wDbWWtILE8O/oGvQzpxwNmazGx0pmLJq2i5YY0MyVMjmG52y4eWtEXl8xVJbP+XShXH2tVn3Gmde7GWDcgiPCNIQfssZUriOROCcsgkw9Ii08NZc8SKK9F2elWqe17HZ9D7D3mWSP3Of2tOVWjQ65mZ9IhmPUR+YMYf2kJasQbfmcx2oxZbFtaSEU67s7IANFcIGbAw3pHOLYUC4sWQdrl+1CnWDpGo+CgNJ8lOYWwVdHTvnSBgV9EWHQbI7RFXyYosEeIIl5LZiTPwOtRSOU9LWalPmHUTRjALr35Tmree15qaEHGVCOwrKu7jJe+1bWc8NRm0RsDfebCSjiGlkXsAhmj3+TyTSO0LQVojIGwF5XIxaCvPLhYsbCqGI50k9ABETmUzpwNSX3QJRksgkG7Cx+bVmqTySok49Qk+YcJYr8X4Cov/JQFixpCpqFBeZ9DGMwxkDDpu4t69zJUNR4OKwXcj4fgmKPpwBgj7zqBEMRkiU9v0wI5gcQouM6JUzutkFZK5AmpGq51EbNAVu7YSjai2AUxWE8Acb30muyvz+q/3maxKWg73Pe+OpV5rsbBerwsqLAN96ITEW0b1zG+aTYzBsdlzWyztzPVUXzIpWNh8E4iXI2mRege/6dbsi2Ayy4aNTMR/tmtaIapDozcSYbpUHmcsScZ5uWpt0svy/kQYIVQYzE7YXcJCvLSRoaKeBWBOiQ7unOu9mJFXAOR/7OhLyUJbF4HM/BU23yL/j1p1oF/+bJQ70RdE+R4Gt8A5lfSRUyejeFS/Q0g/Ki4RMbPaXIer8hfeEnVffg+epuLi2cBh+CHmHz2i8xLpJ8gVhOPY+SxYxwli1D+qY7iMbc+9+WXbsDy18FmQaBSkpJUwzvbMGOfVR6tf1Zm0yWwaRWYrA2OW+PDq1HjFP1VHiki0xBlxC3Q1okHvuO8mNdKFfQ1xIn8QYfATKhosEoo/iANE4Uxju7EEA8lSIOGnNSnGAMj6asvkVV94UJvd6VTcGdYrhgA0i1Evj0i6fdykxh2mjKbVTl9BEVBVv9+hMxAb3R2dugH/ERUmRZKwYjEWQ6itJ6MV9nxo1ej68O4clocwXGFWRRtnBbcKWoBfJXhMvWC1GAFvnuZNgsHJjZIhZDZl2UN/JOvkw6WG4Oq+mLZvGnVAIqEWNfQX+dVaON//ojWsXN9+fCKVJlJVCMcUURbfFZ3ewwujjWvQYFZG0MbjDcdo+fXRTR1UAhfQnq20YjpOkvHw
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

