apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBBVFPwPwe/qu2mcz4WP3MT9HQb3rXuwbTEOwtZFMvkJ+5RcAFmA8gtTLUt+G6RUmNX6dS8y2b3poYgASmamqrAFx43w9CmxtTl2OhCjvzx48t7eW+5PwVqZtYhPD3ibW5kmQdGv9ipXZDLO2PXAgxHnncm1asifapFMmQrHPHgwRfs8/UBDkfqHa0rTUZrv/caWP8yg0InoPKxxHnPCWVxspZJRNIrPQWedhSfbXpb4gFVr6FGe1kdkjQwki+hfSMwNa+nUFdgApPGSh/4R/FoHBPCub/G1Akevflzfyzy75MRgSFYyTDwbV7qtPhhHJXOXprEiz/7MOEOliSrNZq+R0QU2BcLO6J89Ix41rEwFX6bYOkHxY3qlRjo6+fJTHMS8nETG+JW31JE6+pLtOyyF7URjVyXFcnRiYvtJuiBAHcRXewtasH/xe4ivV7GbQ1DRnGhzS1bvSo42gc+TPJuaVgbksrhHGXVDZ8zwW7gJDTf321LjikT4ubrW6McGNNEgzgvToas/6bCGc9xyN8jaBS59fay+W0YD32KFXyj6pwnzEJFasQaNqSy0RO/dxuDOuvBGe2MD5ekHHiNdWtZ3gKPnL7O+TBI4nv1wRDIEM9W3HJ2rZiQfgeClCcaJNYnxBJnPfUJjqgfvwXFMI3piEn5lCIzkBuV0N4zDMNXA0Rc5onIpboQ33fXi4kJc7foF0T2pIU+P7LzgOCZQtpP+ffpV6oL+lRYTxV3fvYvUkhjDLBJJ+HIw3yEu1GxnkKvkgaJgysn9JuFrw==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

