apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB5mpA+jy+Yg4EnhPQURuDRjXbytDXTgtJQCYR16SOO51L0YOyv9Pt5VHFChEKmvknueN3tQ/G0D1oazQo0JyCgQ5rNOrd4itCsTc/iZbvuE2z0xjiaDvFSP8m3QdxaeoB9e0Z9pheRLnEAigninfBOW5LqAW5HvbswtqZwVvOFWzWHzsObLBpTz4Jo6QELCyusP0PtsxUUtZ5NUzh2Xr+Plxfa0yO2nbX51hb5UbQ3VkkWXWTsoaYS24I+R6BZfCuX0BWHG8XvI1A5ReByFsyeaviTAtvfhV07sQ1obUOIwgiKXkbmiHfOXpI0S7jSonYOK5INtaWZxGeqHIPbrhMfKByr+gXNRKCdr1aPwV1IjVwa5FkVM/klt6fn1u2fReuvS/iiSL2QDEtrP/l/04gzrrDFQDCJvt2ADg0n2AZJc3dx9Sp67mV7nmEErbiTQrePmGZQbbsg+LBt4H/+0WJejrzX+9SgOxs2hDEjnY93ssl4VaGqvKv7x1dZ8FExekdVrBY88qJCQI/Mr/mZS7d2LrbB7C+EdeWaIOcnmRIm0VaqG9wPWyaMNrUwpuV4UL9dw2tRWyxii+FHgUEoik7rBT3zDiIKs7LQPMhAxypr/hZ7BHf/QY0LgMx99HzlIHG7Nd7zzw3V1g9s4LIjAsVAI6YMInAXxNySf4zHO3zCBfgYGGcyirfuoJ2JwA3+u9ThLVSUqwUSQVtsDei1EIAykpY08iz1/bPBb1gd5mj9q07Yf2s+xLjKLH/27+BtNs1V6/C/KRJSrvhK8DmC2yoKZctCprCsbHNTFgA6zCT+T1OspLYgJ+xwSiUQ5k3GAZZ+O+/pH2rX8nQfB6PMxpGRvn18mqvQbU8g8gXBCCZ5FTW2DxMr9iOlHG3BUsU8K3nDyZVgI2qLAUgg73+BFe2P8wZwedmxBuIqrTIag78AWvTKwE72vk+x99v5so+bSZ/3QYhMF85DFGoLtxE3rX+CmxgtFjf2nhHaWxK5BYnnIrvBE5sAhk2UqpzS00VV2R5Q4tyEKeFIaQyFsnIcYMYdpcISDy8bTLxTotzrHeFrTDHNAhqbtANhJjo16Z1NVGDGF6YWtVlsoNiI8RU7jByyWgPzmrNIgnOXRW5O7fJYPxADX189u04u+bVnyTniV6hsOCOefV5FEZMGzaoU6atJIdmgJOu2F0BWjXwP2moDV/MSViLksZI//mIbqSnXqqosRz4eqgOJmoOvUgKdZDZi
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

