---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 6.0.1
  values:
    timezone: "Europe/Vienna"
    puid: 1000
    pgid: 1000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    persistence:
      #
      # config needs to be local-path, see https://github.com/Sonarr/Sonarr/issues/1886
      #
      config:
        enabled: true
        storageClass: "local-path"
      downloads:
        enabled: false
      tv:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: /media
          readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "sonarr-helm-values"