apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAHucpBkLJfAiPI78i2y8WbU+C0a7xbLia5QAYLYygHfY7htp2mgfOj8UBB7UomMPZ5NnVOSDOQfSETXLiI6bfz38NbUzWlPLscXVZIl+Y/W4oMp4sFKFyEIwXUcOuXrxZghtTteSGVZg6jZpbuKoWsBS0hM/u7Ag8xKCs9qqGRl+LBEZPnKcGg7l4pEI7S6sppffsa9h1b31KWBg0LeQ++npllEEHWHnvIJYUd3FQm4IXLAEAWThmbEbG9IB/SGddiCWAgfEksmmXmV47tBxODGzaLNyk+aoXLasy+CWRRTEiGdg87RSn+Qk3eJZSRwEICRIvJgLjIKOKBmDAYM/0tfcZXfJ06fKGzjqI+XcGXDsPk12jnFEMXL+KGzl7QqGRKFh+Y9yCBoSaDLb8S6HbOpRyc7LkAkxoSo3+NFK7Br42avogYdROwfEnTdlffJc3tsS5jQplVP7XY+YP0g7fBp0S+6XaQpX2RxxaA4wYrfBLTaig1HyP2ar/PwIjxUt9jnqwtQyn/7OG5ASkZukL5IhtSYVmtl4UtNk7hcItPr6PwXPFepgjX1nxbOPC7UjTKSkgq8JuiQqHNiaYW7rKdZbvT+jgWd9CMgAfED6iE5fYFZW7F+fsB0WSJVuItUrpzPpzUcBPKGyp0p7Lg3w4hjoAmV/Ryzt3tCg0+iDpqfVEkHg2MOGMMP4HlIEU+M/3RPNGMrhQ/YHtPdVYJ7HhHeQe/o+2S5cs7s3iXZV1RYPoRwUDx6hLsElB7IrGxl8s/7pQ23nnuyHnORvu9Dxyt/i2P2IyC2hMrv8J3+ENeeHEpMUoycu2OMkeXuGsnf1fiJ9QPd9OIbwbIFi5ybwKw8imkksJoPJqPSHOoPsZU7SNoidyhxCd0x6Lk2ge4+N1B14VKQ+S7S/AeMoHd9axXNgUXBJilMyjE8pgSjiKYwt/TbITYVhV/lgUkSRQJ2134tUB5Qnv6ZE4M9TEksGwhggblsuYuZtJEJg21S1H7H1VvmZ+77d5fcQfjwPf1o8JtFQvGmhVwU7+hGreA97OpJqI8p4G1uIe0U/ICrDwCt/on40FGXVDl3YjjqIogWAMTi4ckj9HHfdDnXBuNcJ0gEFcpgYvqQN6eOJc7OGvBIyeCvIS7pD0Tl8T9Aj0/HBx6xzifnextk+g1JBI6A7C610wnh66xT6sIjBi/24894arJYjD5llMRQxZifCss/fUbn/hQTM8Z+Lhq0cZ0LulR
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

