apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBMfMshSjbGotSd/aGXw9Pwoa+2Ob0CfLdlIn91Y8SRCrzVoPehtlDFc3ZgHnXAIu6tRo38EA3rBLbUjvCbAfGVwTtYoMKPbYRh7GG+iFeGdyT1b8OLCdhxmLvECChIB0F3uU7olKCyizb04M8GSbRY1onILnyOwxyJ6EvrWzeW7yRto1c3HSqyKVHJ0BhkVnBlKk3+K3+a8ubYH4+OGrO4RQIom4PqxzhCPMOXft26kG5kXyrggm0CjtxSE3tEEIGg7t1V1QW+aZ9em/8FEGVUigE1hb8MEdhL7bYttMHwEA5xOawezztFVPIvFkwlPXQFkm2buJGRYQfUt3hFd08UKo2eVc1mqeh9gsfIBM9Oz7v3xdipccmEbTL9jOOikesjbojZRWEYHics0q5VX4s8/A+VfWDC5sXzgz9ZCG/N7WxN548ZECHL58egrv/cbWQyoBTviWCwSb8WW8T65RiaTNkKgglLiiwEirdYdbLg9hu9kHgOcK9RTLgejrYVLH+4NE03C8Yxdheu2sYt2+xlLAn3LIuaXdNXjjPRhltO/w9xtbVxpWh7gm0z0RtefuDr7S5zuy7ddaTLO1pDosYRiJG7dOzR8QIKSn+no/0viDnMEUaIFSaPvYJ3+qBexc+P0SPM4/VBv5w/9vibR+STRYRGlzFEWxeIcbRI8PWYVEHAjaCtRdQfwaiSl7LdwRYuPHSGEz0V1hG1rS/l2jh7K4weKYi7iYaywAifKKB6RFCoecwtKbeQZAzLezfVIzYJedT4UXwtaMjqWOm/pXDM8zp0CdAkVlHh+YLOK47D
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

