---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: sonarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: sonarr
    version: 6.0.1
  values:
    sonarr:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
      timezone: "Europe/Vienna"
      puid: 1000
      pgid: 1000
      persistence:
        config:
          enabled: true
          size: 256Mi
          storageClass: "local-path"
      additionalVolumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: local-download-pvc
        - name: media
          persistentVolumeClaim:
            claimName: local-media-pvc
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
  - name: "sonarr-helm-values"