apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB86xkBMWy+QyxXpeRshcLzKvskoBy9nQYv8EkNFHP/wLIdN2voZ746+CcR7OeGJ5ohlRFwe90blqV71tDpfevPLrWwRwE1dVDO/GR77qaAxhVEec82dnzQbHv3t85KGN6EhxR1kvGZaycHm8TQSrU5eUMqZoIiHgpl8FqCH6WSVIKo4xicsz1AyjCbULmjke6Ha8Qaxz7fyMMXfzkBQGSjMqz9WntmyoZy2GdFceTPfRCm1Ees7wkdqoJ/uwoLwJJDjAd8mk7IxXvn+wOEi7cZNL0bVLVseNvsMwEh0wVJwPF0g3mRIdmmmOW5qzJRg14UHFMwqJsQMu2Kvh6ZgiCtbYzqvLFjFuOaHLwWhs0yPA0uluTnSve/m3S2vQ/IONwD5akr2wgdjc7faeV+yAkHa1479bHBI7Jl3997pmPSf++NOIcI3um1QBmscMNeb59AeNCnCXrg0bEd9zpw3qqADYW/ViV1tuY2bwSu3jVOZnRLzWD0Oh7EITk0Itks2kx6RkxiSpYhUWQe6l12DWkGcn4/v2pp+1G3IzfCbZX9AWKXF1OJYqKDZ7lurIk15GvB61gWW1zj5/K5l9J6fVu9aIs50o0q52Bq+UuAvzAgnvzuYdYlNO2YDQMvJkTqtrbMHU2t5OyOMZwikMhOWsnRqwLNkiOgsyVAQ1hEWcMzCTxa9nC7kCcIP6uEkklUgjc76ijqbLd6bho7ifKVpbRmzqs3ESCPAhhY3w/rqhCNlBSAzDENu7Z1Xmyu/qAUpGow5exTp8GltmD+pw==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

