apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAoz3/DlzGBSRv4mP7VTnUHDEwiziqsQqhEe0V2YIs7t5cZof2g5RRljSziQo80zxwXC+GUFbH7ktGtAcIvM/sVtX7EyWCtN5MKAdzIK6ZEDdOVkxff/CMNHKj4fs19Ni242WG3zlbcfpTrMtxZsQKkXFSgQS5JwFb68+TKmOt2XQOtOcTiEpwJS+COZ59DGChfXET4w+7+I3+R2CwyfNNiXJwrl1mDYqB64AoxZdLLeuKToH6wcRqC2QZbPysPWe67pYNZ8lB1lHqR5/bXU0nGuQQvFfSG8BLSyjifMUflEA3W5SYW4Z2h5/u1XXe0prABgtzvJsWCPJYtWihYPt3rR8LwN11DYUTrtf0cXF9LMbARpjziPK98ceU29TMBqOhckqSSEUXACXecI+gj4RrB4mryjLUsKhGjtv4a+cceZDhaLE47yi5GubBh3HSxMG1Xq2qsPZq91GyBY7c8UgOkbXIjbklasBtMviFZ4vUYJBLMGv+q3EhrdCwBTXV8fe0u46VLwe9ywtXiEyTHRsj5kf8RO+4Hyxix8otZ8nKmDfDos0wYTnk+JS9FBXoT3ImFptFDIK+8tVo0QWCNCSDjhyaBSf39yBb7b3H688YaaOcrrlfVRvM2a5z2xjiHkj8nPJ4M8i/xwrI0TdAHHis1nUZJg0howbwNu3/xevGIn7fE+byPKsJU0ia2JNnoO6odTCcXs5o3+5/U6+gSdhwtK/3DFK0JZGTaDbnwONDwBGr4ncGSfF9MvwhWm9uIlUp8hd3fPNM8vjI1Q6k9yw+/U1OpRbtpLEYmmzm1VII4uzNbQFLs2bp2lQrj9pw6cmuz+E00XQlW2MVSZd+CZnukarJC93wVU2u1QoQrXianuaSlINVs0x90HrN4b6Felx3u97VCjHm8PbSr1Fy6ewq2mfxWQ03/LkKxBE43xRVgIRnWhN7jg+3gJY9MfTCnv5YYew1fAiZVleKs/8gOvB1KuzwgIbrCZH0G/mHmwGeIRzUJCPjqiHpJjsolx1WZSfNJ5DJ0exVcU4JBG3P01szjIciVJcgODp6kBjDWsu0ztfiaz9RNXj0D3Q4caOxAqEBu3T5cpdQ8E2DjXHiRTz2KGyOsvIPqJhcQxm8NsOZUf5EAE11Fm4zJgAjXvEmOLhwwUqaxiYLWcSarCbOfUU6TDRR1Ue+KchsM6gN7v0IHWZCE1XzhCLu0+Nwjk9dMze0pBhXsOR2NLcrYrJ4ZGyaE
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

