apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCHrG4YWwnOAvQyspn9qiOkGlGyNmBNKfxJ2DB1DU135H1uRh9ZD/D2Be9v+rzhnAY0G0SOUypOJW9gk9ksEHwZ8U+9wXxKSSRJjhZJ39XHCjctG8Vou8e1b46vhD+PRK0K4X0VxAJauAhS3j4QJg5Gpb34B2Plhgdq5FtDpNLG8w04RIrU3SxpaIHGgsp8vCgNUd5IcdIdmehybSugdeg7O8XqQhpkdD+Z2r4iBBBUR+rMwnRV1w1gueGTTJToSwJ5sXHbL+vE9Zq/nT7NR0Q2DHMlC5/yza2qeIa61ZKNej91LMwm4xYICoNhbRLGMicfBt2oSAbFcGDWTzoDWqtAGZj4i/5SRIslZJSPsvThEQ6rbTYRncHcjmLqEeB+HORdj1/iizriY0KQXEaCGwfe5900LVhPP54TycSAhToNQluuG3Lm6vkhW1nRmYF/ee1Rjjr0BEjZf+YMCDR6C5h+iEZsCnQmtQE6tQthIGHB6+SeNQbYrc82pq74X88LLDM42UXVIoxxzrtRlTrsadv66LE0SSoTYXxw3/YbqDQn7LHJLeUoFK0jU9v7tcV2aZdqbR6sJ55BKDlNkHl0KNb0Fg8gQqzxqiMX4LWy95SHAyjoSKj+AJ9YjTPmV+ihqCG0xsDRAMpIiaVw/FdIKaaSAp2bNc8OIH1JxTsmeUKN5Ri56licmzkE00esRLq3UsWRtQ7+zywXizkZXI3sh5kO4hWo2LaRVXjve0ma9zMbMxokFRcEAvpFD9xziM5u7OCA9FKlnIZm/ucP3A==
  template:
    metadata:
      creationTimestamp: null
      name: sonarr-helm-values
      namespace: default

