---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  helmVersion: v3
  forceUpgrade: true
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 7.3.1
  values:
    nzbget:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
      env:
        TZ: "Europe/Vienna"
        PUID: "1000"
        PGID: "100"
      persistence:
        config:
          enabled: true
          size: 128Mi
          storageClass: "local-path"
      additionalVolumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: local-download-pvc
      resources:
        requests:
          memory: 300Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
    - name: "nzbget-helm-values"