---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: nzbget
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: nzbget
    version: 5.0.0
  forceUpgrade: true
  values:
    nzbget:
      ingress:
        enabled: true
        hosts: 
          - host: nzbget.home.a6.io
            paths: ["/"]
        annotations:
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.middlewares: default-redirect-to-https@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls.certresolver: le
          traefik.ingress.kubernetes.io/router.tls.domains.0.main: "*.home.a6.io"
          traefik.ingress.kubernetes.io/router.tls.domains.0.sans: "home.a6.io"
          traefik.ingress.kubernetes.io/router.tls: "true"
        tls:
          - hosts:
            - nzbget.home.a6.io
      timezone: "Europe/Vienna"
      env:
        DEBUG: "true"
      puid: 1000
      pgid: 100
      persistence:
        config:
          enabled: true
          storageClass: "local-path"
        # downloads:
        #   enabled: true
        #   storageClass: "-"
        #   size: 20Gi
        #   accessMode: ReadWriteMany
        # additionalVolumes:
        #   - name: downloads
        #     persistentVolumeClaim:
        #       claimName: local-data-pvc
        # media:
        #   enabled: true
        #   storageClass: "-"
        #   existingClaim: local-media-pvc
      resources:
        requests:
          memory: 300Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  # valueFileSecrets:
  # - name: "nzbget-helm-values"