apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB7iYoPq3BKRxogYCgfjidV6rDwIK1iD4F9J0p4tYKj2LNAcsnOvSgsqJZL7FDsihKnv494K1qktARxUzuvN+QELEEWpEa5ZgCuDo3mS9cIYQjke9rTSailDw2aWHekEL6Bo6N2ZfaP9kD538ELC9Pd+z0BiGfZmbnfQlBrLheJh5nzdNNvMaRso6kKHEHwhFFn7AUdF7ltT0kZeuvgBjrrKWMUX35oeDsoW7k8BqWr1Bdx+x8rLfPjOsQd0NvrKURsBY+bxCTIgwskdJM5sVy9rCr0+ly0WvkBNsDdEGlQ/yzqwv8vtyQGXRxcqn8I7s6HxAJlCzX4W9moWokzDmXSw/o1Yy7zg8+hHcjeSSfB38XnFZYqiwhZkZf1irWsUsKuZ2IuRWq4FdKYJYbB5wA+d+gcvwoVf3BkO3f89sxrrZY5yjUhB6DoaOZGbGIgBwajnQ1Te8x7NexLujAxsBWtExvE9+P9bk/RNrSGmdvY20VgyrkdlKz3LW9YoSjM5vcCqvMKr+7aRvotmDi5MpY97WMPoVhHqHD458X4XK2Hh8N248iU5x+rL6nM/mZzjtZedmBiOVCkOFlTS7Y2byZnBXgYIZdffWCg6FWYjHj/+dUBDLX1p9eaRqmm+F1TX48eRnL4GLlcAD91wU/7PpkTpcm4NPlj8sQpJCJ1+YFkYbRHvs50+fQ0jqSuWY+lc1JZi32xlGMVbM0iK7MiFMN/ENxhBfrDo71ncpdRd2yttBJzHCRls9mNI/XmKx5qWC9KWgY8O/0IDFoGkNU8H2EtM4ZGJ84UTQ6TfC83OU55BWBOUuJzqo5pUOYve8o4LPBKZ/D0WA5dBFVpfUB3f0xCnlXZHSoWC/UH6f/9ze6Rg1Z641Gu7PS+sDrL3u5Ur6m1IsC0t8F/9w+cJ6ARxa84mxUWj/Vzclg8WXNhODRsUH99iwhx4RcYfi7FUsd/ivUr7VTBjclvnRQIp8inpfgkQZ8N10vWHR8vr7vzlOydk6uj9vD9TJEhgfJRM/dyU6UTUNsjfzMb9NQnE0GFY9GFCMImdG+IJZ1bvE0TWs0cCPhUu9X29x6Ux7s1XxioCVgW8+v2njHW5ZKkywZ9ZVEFNM4jSepS/ps8OT9Y7eKwwy5psZyz2vY8vP9/imendbEhS2tB/rv3yhx9VlRehJbWpKCSgrUCG1qBhUPgXWbqPFjbZog1WZLNIM3lGxVKmWGpcgloZVcQ8ufmxt2kmrwqWdA8YjGxP2KCiOXZE78qFRsIhg4nhFJG+3Wd3A==
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default

