apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgA62k04GtSIUf5DY1IP7WAmQvbLP+anUaPYUvsu+lPs/wo5LeOjys5pRC+2EdKxHe229dLGKqm3hGVwFslfzo6h0GpuG15nro0hJwvOvCVAglx6cLv6sbMeIIWFriZuqj3WGf3AQcevZ9MJebN4K4YLhb0VFt2ZU95PRqxccEM4YHinew6QBqcCEWCiDX7QZ9cCzwL42gqFCDxviWCaDlmOjaML+dxbuKiMtNJwyoTLRI+jcbOHffBjWJr5aTkJQDP7o3VXrtiNzeaX2ok473pRFcZLH/uSZOw++tIJ8f2YvyE9jukwpk6C5bcbSPBGcXBse2B5tRSR/eP42IU2r8ideMossVS+dxCvx2aQ3e/lr0uDnHttrHzC7wTydLHFgDLSlff1Mj4tsqjvgnXepnWo4KPIy84O7gmP01z1pZdTpFy+PZwmN4k98eQm3dOw0Jr7L+xELQi3ITmjGrzs4wr4fWp5rSfvX9QWzwL4wNhTh39p0pgzFCZg5I6+YqX5Y6cVPKTV0ZNGfG3LWzuS8y+BLdIzZ8y5U4IMcVuNlCDTDtVMoiQ5EtVpm59tP/2+jwmirdKdhsWWg7c9diY7+3hzzNX1+Ze+QQXgMVM+1vnQA68QaohzfpKfrxpuQxpZQob6Imq8ayafuRuD99SgKcygiEOl5foqfZNW1O76HD5NsmQGgHojiGjKosYSSqsS/80w5RLWtseCWhFhyRvVW0ovfNtjb/kfHbeSr56oqH/YXGz3aP2BuvIf80Q+jX5zCj7wzxjYgK4T5dcxxQ==
  template:
    metadata:
      creationTimestamp: null
      name: nzbget-helm-values
      namespace: default

