---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: native-local-storage
  local:
    path: /pv/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: native-local-storage
  volumeName: local-data-pv
  resources:
    requests:
      storage: 20Gi
