---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-media-pv
  annotations:
    fluxcd.io/ignore: "true"
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: native-local-storage
  local:
    path: /k3s-hdd/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-media-pvc
  annotations:
    fluxcd.io/ignore: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: native-local-storage
  volumeName: local-media-pv
  resources:
    requests:
      storage: 1200Gi
