apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgDBzKFrfeWA1CuaPLq4nFn9ykATnvbAs+Meh5xIms3Z+WZ490HKtNm4uk6dOVBNXVMlAnAbMVSOyjrioBvIxbm6VZYCAz09omytX7zSAHd7QhUfC82ZNHaNDZvf1+DHmGd1LGE7ATozNaZt2oLTxq3KOF9LwOhU7GfKX9pM36RlH+sKfvbYH1y7qR8hJ2dNG5o/Ezn/TltUQSsy+22ofwUEgndMNCEQjE/r9ZyFRg1+RCJbdmsOOGuLONi5aL32mh512gQ8PKAJsb/9Jz0aWzKBb8UPvOmFgMJY164zaarO59e2I2T6HeDdqVDrzCgclfjeLsx+IGXs5SW3lfxfh00ZE0KFd7cUrq1oK4WvHryYoR7gi2+C1Mec0QgF23IXbexkcB/Cwp4F4crUueLaI29v6QCghYNG2oYpUo6zgeniGn957cvSKH5B8YIT1TvZ+Lx7DUOTXL4NcmXrGTtsAlpoyPJTlMA9gtZ58FajoVnqUf/0zoy3Mf5RGZdbfZXCHwIE/9T8RjfHoXEyOpxUrS9bV7x5zHjudh5GWJCKD7OooBL2Nai4B0iKPRDe2E6nec/a3et887sjY+xQWVCWxA9Jyp76pYRShpKK6RDLn8izZyylBY9bGENmhXieERIva3BO98uNVNOEEkIfmTfq+jirmmjo47M2chPmbanA+t2ugOz8E8h9beYpZFwH64IgO/6k1dIyHwBov8//4WQJnLY3NYt7qhWOxnAsVES6xj4jJiHxM3x1tuOCxH8f+hUqis/pu0a173yknm9DLQ==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

