apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCYyasam8ssWvksMaG9K9D8EaM+8dWsyqNVCAfG6YtoQf/Y0J8ljwiDFzqqWfScp/IxptR+nh1Y+DvbWUh+sqJbghaYdy2El1sWZf5W4nd5xTxD5ZOeXc0a+baxgj+NGyX7eG8PYo8sw5p5cUtvRnJKtFyseVIOMA0COxKa88jR3SP/q3aJaYp1yeMkqCCLGQLhTmPnnkqHR/X2r9fR+eozfIrpwGwYpVa2ZbgNNOZDYGZaKyjHz4qtlUlcEsXWU2ftjhMgqOAb1RK06q1L7+WSCRSWlixrPgTX+jdZDZ+B8MBhqrq2vLmzU4IvSGxRGC2cT3Iesh9PabKu6lvuFemBhuaQWUrxTwCSAWIRniF6He7PnEUGGLJhXEu4fjsKUSVQv+63CqwD6bmkZrW7egM2qh2J86uwG4/SNPYB9MQ79r6c7a8ea4vQfmW0gDCNffzEHMQVvlyDZRfcgkyPX7i20eNQCVwVeKG79Vhmbw2ksT7fmZJnClwy/gPTGrux4D8q/zAn4z4pdBK2Zw3OYKtw7fURBA+hw5j+Y4551w+t5XnQS4mcLXUYtbw7J5pxBerRSFGqvgu/0Hjsr6CuCE+G0fzIrPQSt0cTJnixcLepnDwXacOXcvBarBZ78gG3XIhg4G8gcpT0LZWUq9hudm2EpcR77cDqMYjJ9g+oHrhCrFho46G7cOwedADaNNxVMuZLargMdmdGlkJewquLTFUJ4ZFFG9ON0677sHVWN5MiBRma7yO6RDYbsNm9xzk1G+1SaCr0288HiqFMpzoLvjGv7fuvFLr4M4LlNVVC9AzHmea3oMx9r25tsyB81p/Xh+f/RLdCXklHUnsb3LJt+OZLEhUbNmASQwCoKS/uarjz2n8qD2IsyeC9GKBgZyNSa5SUpdBiP15yJZq73lOmGI64K8JJKjn6SJqGW+eJIoIrHGVFGWsxviFDPA6NRaTm6Z3e5iVoyb5Bub5iudfxQOdPTY1Pbz6zLDgax3o5tRiOFSEbvUTxY2EAnL9VLG5oFXV9EbUmwAKaEfKfHP1nbMh401osKzzIup4+9xNkVR67GSKJSrBe2I1zwHss7Dkix8cAGRLbJCvnlW9YcezEJE0jwkqmPdXZiBEs47eIcZxzJb2G+UooL0UM2mkIdP2k1IYDrKYWOTEWbdTMjBUvNBbljCllj1nm3AWnIvRBooUU0Vyoqumnz6mCsNHPBE6mdHJyPC1i0SaCdD9srRAjgx4VS3YvGKUV3LtyK01XKyZlmQgFEw/vvcLhkEB71lBUJiuSthmOb7pOTez1NjcnABYuhuZczs0idsaSTcTu3g1ruxHQP7zsq5sSOjQt3OsmjEsg0lGaJUWZWtzR9nf9khX6hMFywUr260DIX7LI52lJxlS/GNdoX44x4RN8cpmyCECsCZOMDPoc/HWDlA==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

