apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB3Cnz24PpGAf/avGWxsMVLQapG1JwKM1WLCYc7jBmwsO4yEtyHIKw3gVtN7qmbq0HD2FvIvYUArJdI3YzvDI8eRFw2oxjvLaVsgJQtr0qwnbtXOcJBBPERDGSrTlcr4TznqZmEpfSB+fm2piLvnclkuGJtm2vn3MsMTUQyGNRog5gR626m5gZk4t4D+zdE73N9oM+8f2KoGnKCtKMhnHmoOk2oIdxrAUeeyv6FeAx00S66FZK6ERimBikcXCs4fEajqPj7iJVletylMXxQD7T2wGgfO/pFD5ChmNN5NF/LlYXPvY3cEvOE+TdGWzexi/Mdk2p6ICDegClE1JWHSiuLcDXD7nysexRwrMEZkBr5w60Mp7PuKt4HAdcdYWgulNnEu13tj/yyBcKf9mxJRSlJCPYi/b1eyuBJmGZzOTnetYHZAWgSu7gV/FMRVjZkWgTs5ex6eG/YuLQvL4R6/AGcJx3ReB2CYD+vj50rFBHAlm78p+YNz8NBplTpFW6oRlbHBx+MoxJzoCHHwmp5psxXjzAcJnb+T4d5bBszcC/VCVO6cXPRMOHyMR5pItww94N+axn57SVXcOeJ2Hu6PNnQGw5bynFB8a5oNFZK+RMEz9UKJAXai1gbuH9dxLkosd28NNwSzgpHdkv85M/NxOKUqPfcbG6cAlkebhstUfsO75Oj6iUVOvda+HFqX3rJysH4sg3WBPHspMMxPLi1ZwINhxsHLO2Tch5hvriKx4Va8nmIBzPeoprF0794+h8cJ+1JpSLkqQJqJ90Tww==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

