apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAzcSYSNX+1YCQO2EwXxI8hxHf+777ZqIWNLtqj1cnUDD7zobWqH8im8/Bguhte+H06VDfXPw3HbglcsvSwb4zRZ0g7sjoC1qazblY9OWp1g/kvejV/KByZhH1S51CKfTxyN14vKfHbrG7X1vIv5uz9mvp0+qJ2fHjm27VSzaKrHGIf7fKfTwA0TJ+a6n8Aepub89eb6OKPx+TKZFEONGCnd85pR20WLCrn6Wp+OXelEr93tsMmNeEzzO4e7muHZEcolYEKeaYpO5T6/3zQ6z7vQ3Ye7vdIyMRd4+TrZKLgN74r4y8PTVBMnzoLNi8h2fAFPQughsBFD4iPF6Ubv2zIvq73PZ2hkCQmby+purdIrSn6mjiWbGTAte0pYN3sInL+U8t0XhAx5jFJqIpE6OA656I9fyOTBBBrMZPLjGV6fcw5TDSs0lO6ycAzeiVTrWhDS23shyfd4Yk0rkrqpfwO7kQe0ZQb6NoxEFwhXnn8F5wEW34hENDKFFg9suyPY3higAgrkALWcCmyOb+GM51Hdu9ruIncyKz4ERljsMTNIOQF5IBU1PcsmLqdGFjyIdxSv3xwTZqTpWQknskkHWHnPgKOTRGxmVS9CGDXjNynUZzU9lyrCD5Ow9AdA4P/FAbUmeyVMechKpPve0XxkKpuo+74I6BypXmoWG96RyUuBhzxsWG7O2PyjXAIEz3CnXijNBpAVw9zv0yo2T5m2djj0Ymv2RltTy/K5R/p2cvTDQCjhO89adEQtRDXmMenLfJNYQ38ks/+pKWcFA==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

