apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgBD1c8R8GijYgVmIxZ/HEuhxAayjlXiTegdEa2+1T2iR1HOBnmVSz93B64J91IVJy81F0w5q+MCGlWVzBv/dlBsBSx/vVyWpr/JAg/j7VwCmKaxsXjga5t8C5soaEzlMYr7/bagYhGOhGvYiosE/5ndBkxC99BfiSaVSZgpDMG8/Wl/sD2mg3oEkWMwEyoK3YTllykpNyGHjLxt/I4Ue5yQhf0DvZBz6/G7kCGa/O7/9MB6v0bC0fNET6i92QbtyFzrShVBqXlrMe/ZGm+FvmRZIruL8OZ57YYgR6bXrLx8k73PaGT+O1wevvSqU+1lTNXCcpMO4EQ+DtAXyyiUo5gqg1eTUpZJGbZFy0sj10egTvV+ABAxwlIzrDjmumJEtD81i3dttYJ5rxXZnKS+U+S9JDqOcEuXbLdtsjXup2rPeftUkwV2YXCT/LgbUkgyp1L68wALoR9w3r+qytp6NTMVbBgxEXcbUAgzWGxAdwVtHisWEaENdCcxywsxajI+f1MhYohU0QUq3RF+EvXgvolmweKwWVTCLRtHQXi7H3K1vTWRAGl+g/yzWEVTz2qTjN4bIZBOUATNlA/dKBGJlWcMoSVxa90r2Br5RxacP/bUYMAi9CSk35KVZC40TvnyzIY5OOjn3JhN9Cw6JehOXfYwbpEDZCLgYGnyT+TF3E07SBPitc3pAWD0hRILI6cTBM78Zbv9rx1xjKp7X95plFUWAmZcTft4Qta3P6YushAOjUCyo67x1DoOgKKPR7Z99RXcM66yiZXGYOQyK3XvyKK0d6Fc3eyiuEqqIGyUXJo3
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

