apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAUPhAb70k1Zc1zuWOdSn4UTM2w4NcOgMjXhtYaAibKVMrl1hKgQAm9N5bHqRicDy6ETkvVpA3zGBo4+kaNXn6IXUrsa+/oXrOIuqZFEcvXAk7IHLj2DC59MHUWgqsQzL5KhyaSHkkUGXpZBZCo0AUUSUbTruThnIT1j8r3SLohzm1Wae2E7JlFTDs9mGW34pbxjFaJ94MYqk3quzRLZn5SeiDEiTTbQeehuKuCIv7EycNzSF+HyPxjiVwW9cZt2jprf85gyZiAwDU43iYzeptF54rt+MgT3bmU07kNZ8A42zxaiAdNLjsDcVALjC0bgH5qKOq9FcIqnQGWyXJs7Cg9gV4o9QnhR7QmhjqZ3yIkc9kGmyLFt/4TxPBdNY9Ai+L09xMTGWKtcUwiask907WFSwYn2UBFa8kqPwP/856aV4V2bMfI7WSZlDR8PR2w00tipL+78VvhiGDEfN8PaYWRMnCo0sBYWSH0u/vVyYB4QVphqe2II81PRWVE3RwiMDrmDDDpyGkyFgjQmNgiqhsocnYt/C4AEWZ1SB6YI5iR8tGDpJ9YSWUdb54pDaPTauMNngjzhj9OLeceaRNVVgjnSHRXnYQBHV+mx/fwkHi2VXv8sFYhfyjQ3eItlA6GqYXtxa8K6SRgvRDXDvGukB1oeysTBuNrpGT/K0BEg7VoTDp1NpM7UCeU5gxO9kMh5xl7wD7qCpR7R0Gksd6d18zUnN70j7hYebn3tIcoeYu/RTwKCwS+tkSTZL8o/+rS7hjzdwUdly7L2WCEyaCHuiIA8g8nXKCbuVoATQYNSLEu
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

