---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.1
  values:
    timezone: "Europe/Vienna"
    puid: 1000
    pgid: 100
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    persistence:
      #
      # config needs to be local-path, see https://github.com/Sonarr/Sonarr/issues/1886
      #
      config:
        enabled: true
        storageClass: "local-path"
      downloads:
        enabled: false
      movies:
        enabled: false
      extraExistingClaimMounts:
        - name: media
          existingClaim: nfs-media-pvc
          mountPath: /media
          readOnly: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
  valueFileSecrets:
  - name: "radarr-helm-values"