---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: radarr
  helmVersion: v3
  rollback:
    enable: true
  forceUpgrade: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: radarr
    version: 6.0.1
  values:
    radarr:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
      env:
        TZ: "Europe/Vienna"
        PUID: "1000"
        PGID: "100"
      persistence:
        config:
          enabled: true
          size: 256Mi
          storageClass: "local-path"
      additionalVolumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: local-download-pvc
        - name: media
          persistentVolumeClaim:
            claimName: local-media-pvc
      additionalVolumeMounts:
        - name: downloads
          mountPath: /downloads
        - name: media
          mountPath: /media
      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 1000Mi
  valueFileSecrets:
  - name: "radarr-helm-values"