apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB12jHPxkSh0aVa9l4RkmHmjvsetAfUHbCgeELNOv4xfu2ZPJ7NEyQkYKe7Y5EtRLqMp00pjaKHfhXSGIZ6uKoYc0S58Kkk8cTYWwAbHw0uHWV8i+EYXYsz3cSD3dH0n0wE71UDfQHs24dQ+KlWQS/u/UKVCP+2U1g2LohwkUILiZOJyTreRp+YX4lQEVSkAEpBl1zn3jReB+dBpW8tCMih31V621F8YK2ZZrr11U78p0fW1xqYp9oHYFb9TPMb/R+JS61pfqV+qEK6doUM+wJPSbEGbMoxmlDzTtUHEHXvzv0eZ9PqYvT7tTYQ1PRezghMas6EiX8n9IeHshlYPklPZzBC8AUL3V/lGyHF1WslQboB5MINqkM2g8AfmsS0gBSNakY30fhcZL8/kCbuVvY3bbDKVK/y4+sdkpy9PZu7huwBk9OY6EL/vabegpxamqzEn9yyhipZ+JgMOUyxauMGgj0DGvg6S4osQhW7xAjAEq5Yzrn1ZBUH0EcLPtEmMVHZqvyzRf969Y/TbEOd6POQuZiJov6NW9pP2zDCPBrJdVdFrPKSrEP7kML6BVAKDX41pzIR7vhTOAzGcc+x1WUo0nL6vsewzTteOWeEv23zz1/+ViEnJJdbQBnk9EM4g2ajwX/82ZegVQFqi52Pih6U/FvZsENUiI/j4efs1l+9TkIbszqxSXQE+leEMyKEf7CvLLfN29KyEr2UHWAQVgspCL6L60p3wbS3ITe+4Ss3tRiDNtV1V0V6bh+4QfTgrYPeiz+6bdAagxbYu0RqCP5uyRBh+Ggipb2fhi+Dak/ZFebCKfMHpSpvi8DBoOEiPo0vUgtQvwOgcTSc+qnjmJOwHpg16+1mDSJesc83RK1wkUVvcRp29wbGIhS2uZOW/YN4PD/sTiULNJcTwEA17H+qBrGP0Yo1EhMjXrW48E/GJ7mV/ARNYBGqMuFfFpk/viSKNrHcKZhdW6O6MaMm+j3fSC6pokaALGI78gUW2sDR0jGkGgF4pA4LiRdpLs3NyAAEM1qZWqWp2PVDvcHM49F5ljZfaX9I/VLjK5j3QdZRmRF1lrdF8t+pN1fmUABGplWtaCaHi0nXt5T95Tfry5689RI9bHW6vi/S5PsoNd5hNnxkl0G+Spmr6l1AMIWm88zwAol28VkY1tnt9JCgb0z/dzLYyt1teA9ShPmHUguHS8n8YNKp8yzOgyVBotdrT4QDx5wlsu+k+3w+5HrY7Rg/yPYMOQ4DXS7Fo4Ji00kop/nCd2+wkl0tkrNlKCzNwJZjEJ7A63Ck/DwZQK3xX3RowycYFxED39ekCKpbFbJ/PyMsJlL+DvuPjhkEK1ltfuic4DlyVC0gDfKj4rbRKA==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

