apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgA9hy+m8Dy2wi9LSnD2GRCk2Qys8RvC4NJIJhvQK/DYpnAY5+S41SV0tTISyh1CUD5SFgPV2o55nwB2oluAvBpb9xeYbbbhUCYvbvFwzhnhTDLb87Ia8fXkXpUt0VWtc9H3QWuZAkj5AiSF1cDciL3AIRvjKmYIy5GKhxaLDQ5bwFCvaIF+Tr1Dm44vYaNqrqcGRZ5zA34k3EoCHaFQxLuuxrxUcfr2MslVwuDSkR8aher479ozCZCc09m54zSzyAyjhIqo4i4OYqFES7IGnZYRN9cFrCpLftwicbPIhE0Hx5vgxLGeMD9LNY6dRBwgXDtkLC8dn47eOhLMyFdt5n498VdCKvH1vopOzAzQqy9flGQgywOeupg5oezHaovZfr4KmRJfJ/FoDPJiBcXhJPCjIHB+qzKeTgsrqrpMjJS9dOLRpvYrcWKG7W98Q1muwq6zgnJ8Ik7b9Guu2/87Za0M7JoBY38nYY4K1K3b5rSTyQKAzbhT9eQVHntr2AR8yE1ehVHLpyIYkwYS9YMYw6nR/YosmKL0YgZj68+dsl6EJerdkGjquq/6Ch60mGQkt8xKvrW3VKOrxKDaVTx4rs9iko8hCMHemcMKKOp4EZB49Vz5z96fWo2DVWZoejtbGfvzR9HcB6dPifNP1S2eAw74sQoV0PPnnr64koXiG+pyM4IbOl+lZAB3mGNJ+TO9xhZED+uLWXJ86NMloX6+1Ad8AmYAWWYyM5B58AfnhmSyFLPXsOBA+6zRIgh5Vo0961zkKgXf9JfI9xeGfH/8wAhdyJ9i4/m8IbK7NrgffDa0TrHPD5523QPyQKhplNYTSSdHZj3T6Wg9hCTQEh+jMddz/TRoEbSP/rkxHmxlF0Um3ff+B+RH1HhapwpDWjqTHgzbsn1YovhBSHpwKSiWOvaHIMffFZ/2XSKw0wsZR1HSb+6EG1gkML+GXvQMy/XOV07HzNVTY+zlG9r2KpbLSYi/3vKbkbzwFirQcWZG2h0JyxpRJUYrPLojvBHat/a4VvkvuV/7IgqrUA3Z63OuWxSaCtuugnmwZzwAzGsnoBbqSZpyaW4jCLkgjysCNSBy/INdHu1LcQeMYtI4Ufu/XfFdyk1sDj71LNJw4w0H0v8DHDsc8e2CS1DLd9UqdPMyZd0GkPYo3EoypkUnHCi44sh+Pq8dzHZd31R7T6xm4pmvVNtxff5lBh2kSclRyUwLeG+qQscFDh1By2/QTxYNq8DF
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

