apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCR/hYkUA5ULYhjzXQQyhtHTZ94OEclosqPR1jRG1qxyGtq+uVeZePDtFUBu8Ndf8toFvfJ30F5pHASSTNsVF0+XVeopI8YJVLHS9dY+BXTb4HjO4PWt0J8KXuQNP2Z67K34GOwWkDmuOjLUkyrAv04xHM+sPRl4QXwM+7FB5POJNvN921DaZAEUUY8J6ju4ljfjjMPgzSJoc03HtIWrqdMPimnVemfHmhAJetdhud+zkJL/4KCLueWrOsWPV1kuL7m4Bx6QLYMH0EjbE5/5ZQMOoATHlE2ODrGJuPcWCaHmHfyn/XM/jqH7NDBtFxhqIKUeM6QmJaS72bf+2x75acVFjcn7TNwU/pWJiWG5/LYjxqoTCZN6qqwLSpV1ySVPuTN2SDjXAS5RAcbJhrPtZO2xV7UI+eQ5oUS4Y9KAcvhwDK82j1ZPSnPoRkTwu1Sqmt1yR+bfGOrB5VzGXm7XPatC6nlUP+I6gqdz93pSizpAosGccEWGRP10L8CWDQaY5Jq818mGhQBYSB/vtfv5nj5eV4QLAnM3BIcYEG3VZMFsz4WCtjeeJHhuuXCOmpMfs0qVH22MG/z7mqjUbFPjBnBGHZNC4zQRzUKOjW5JxCiAYVJq/A+1y2r4hAc22svQib+13wtHEHMIDRKsBimnkjsGqFA9+s1S5bQjUkFA1eez2mYS4bY2tTs0pLlfOQmaSPY/p9j1H9QCxp+0WoJVb5CMwL/TZM255p57eU36sqvjNmzNR81+UzNO8XOgmXm7OI0V/f9d2Lk3cbuEKSrl9g2ft8YNv3LG0odo927Rr+ohYy7iYRoKrJknxZZ5vD/iKhRz666ffRhSd1L8PtFFCevGm/gjNokEXg/hn2xTwq8RNI2w8JcUr48Pt8I1t44M/N43ngTvRylt5WEZWvd353tBF2eW8NQ34ElJ/Jz/FwLnl3pZD8HGPixrK0J4QuIZMTy7D4+KMfsQCUxT+RkqtFY7TQUXfRUIntbzwmwoAcOvFBDBV1RxtqXvDl17WVMhgGORDVUGZtD6Clsqb1tLJEpgV+1dMByROCv3bMUtAkNlDtDkpn8m5Veox/v7ErZGR8xSosy5GPZJAO+DEDMj0vp+/rBASyPxWXreIhC4EJr07ks4+LchVv7FxjDlxh77J8/KTlE5o4kn45acWDuibe1ReQqMFPBg0ZPyiuhAWaExx3oL/8SEmda7JXRuxUn3z4m8SerFr4HgxlFovOoC+xI
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

