apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCMkBtaexnHIgC1BF1FDI0hxErmseyREyUrf0/ez52uw837LIOh84TeqwitmmPAhyhl3ziXVb3Ii+xNh7BEqzjKBhkkEJvrLSVPKTb7nE2prQ34Mxi1QuRB99813jIKt1x6YXqgf79MUl5KOg0qosDwMssxcMfwBl7yFcmitWYigfKJNYK0/+cfAoTwz/yb43w0t9keXqunP8E4umvVW/w1ctG1L+RpVTzPgG/6KVwF2rdCO1KkUfVBhWdS6coM6YqYQXF3DmjArpjXdc7S93CSDnnEZgLlEXYTlvAQTVeYvYNls8n5eg7y2y/AMOUYUr9MpgGAjRm7EZ1I3hv2+pqgIvEafDnXcWiVZpV/dzTd02nnhlrkCF52NvLMy62Q1M3+pjgqLoUcPoKgVvUriEtm0oa7fNDaqPbM2PW3vrH7OyOsenztEqgFD743OZCpLZMHRDp7gMtd/7XUXo7Lp3kMX4UXoTW5HnuIG9ZFp4Hytsyrd1I84hVpA08O303Wt1yMBaISrb8I+EM+onqsqDq4b7UOnX4OIEqP2oWqRm0IGtyTGgvYZ7nW5cZXVF55K8OJNyW+qlp0FXbWb5AkoRd7cIZLcF04AoqNPeBmqs63pTPITghFMc/uYREQN2FUuBolIqdj22/byTYAPnsO4YfWRdfmzQFb3gJ6eI+RUP3rHpWczYYJrlPRHdhFli6BhVpAgh493guoTPiYaKX1eDgbt3qtz4eDKVXDuH2BIv9rqQRtFxUjj+RKdC6Hf4+CZrFlsNEmH/goCzKVyw==
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

