apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAUL8oADxGADiux3PMvB4IHxQ9L8oqrziStcoeYVoyaEapkP41Bc+2OIeJB/T5IHHktFoqIiXlCOnXLbYiYgp+MXmpSsVgi4sk7BK/T8pPVvbBUqO0VYo7MBcOKiXWgmyj2XkIQPBPeFyE99L7dwHRUM12fIgi16VRjmzqkERZSkXtShF+pcsEwDCAKW2bzFJeO8nNKwp2gLOusZ5nv+z/1mruJJjqNiCMHG744ZXdfWK2trgndLuZDx04fLQGptgoSH+aIqNLSk/1WVtJw1HJoNxo79tQeDUBRBmYuSW7Jz9zAiVUkLRaN7RVk+JNrL65M6UfxUN+itL+UMKuOQ4guIJrXYdrQkhSjCZxHbhbVGup0b6rqiDIYyQwkbSovtxeT3erBN5TZnBRRzungtlbwNufdODn8cmt7a6RW8ENEHc6B1B3MunG5E+fTOLW4laXSpD4lwps++aRqrBHD8WaQlkLUQ6d/zxav74Ra+myWXm3i+qJQfvwMjf/Pu/0hzHLgx3MQiFDKyWGtWSWPdflairDV8LzFYUeE9MMTzYVUeo0LeFyNwzUSUueXpQaO11U6H/ianmi6OEnEkLYPYMf6oLV56uwyxCwpLitDw5Rk5F+qzmb3AecB8eOyjNXb3cB268yNppyX+UeRYqYcpWP8R69LdojuK6oYm+1QNnhkp6QPz1W2O+3mENggIl0mttfEiUZeBHcEZ1Mrpi86VYkLyqN1Euu1r0hottVAWRHCYu0+lqXKrX/toye2sQycPvvCq2guW0aMoZIXi+Jn7dMOiQSnlwJdff+nrIkLbgaz+ajIeGznTiSnPBD4D41wRC5tpwqau0UuZAFqcU2unjjk+sbYKTaYnsNKMhM4enf4ukHk/gu9UZR3raUP1z9MAoufLEa7+xZwhZpbnxCQNHp0yncWWwJsiMcWe04eLAE128lsQpuPIM7vE2bWppjeeYNe9B1Lwmq8U9gPRSVFzD7F16ZPt4WvJb6p3YE+OTadrcLDXC6lXhkgZku1Dyba2MAM3hajVV4G4c6oObWHG88sfMv+aKTJARTqTZjqziQzJF/bmfB7W7VtO9BE3neExJEf4xTdgeqfh4vaB9ED+G25NwRlf9WiikxrcxYTi0bbaMKlrMyYesjCfQoeUolNPrdBzV4AtnULbTm2Wsf+mLu7m/zEwYxL7RpE4dHNDVr98ttoHdPy+dfmsFdvmlgNZaBLSd4louyulALkEMiW7F2vgfo0MdamsVQXmj+LXKCvQaLKs2ClATu9TYHThBxm3Cx70HaA+yqTBevsgoHkQGjDwugceiZ7DwJMt7w4e1whRkkHptunDnkBo50OozR1IOykBiPkIB+xxsdxlWzHJQSlNJqgXNc7DLSA1bYZ2Sq2Eprp3mQ7uHwl0r6KwApuWHl8Z77wary5
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

