apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: radarr-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAE8WhKCOlhtkE/XEm1efbtW/LtmHSuLt+GbpLKFHkgDVWodLaMUSwSJO9IxYLSD88dLwWZ7TjB51+NwfCWrbb5IDsNUJDS7GEa8RqW0Rajniw04dXQ3HX9A04cvggNiuf/468nyvJtecFEaz/OwPoFVJJLiWKlt2loCsZCEZjLjRrubXaQfxfDaTBDiHMH5W6V6xm7kzVsdYd6PdlGEV55UKfavzQCNhfSf2naxAi6IWq2abM7IK6yKuCufjQ2v+24S3/VfNYtFmbsMVgCYfit6U8TbGYVgD64PSvH13yQTvRogg3n9u4x2e4m2I2zYqMUANBXbRCHSudSSahnQz0bmnlWhWfyldpn+s5zYEboZFAbvXIn/q0VS4/ikdpBg8cQTZcc3/l9Jz4/1nuoZ67RqBZbcZu3TZLYGGTyXx/2IA72C+xFnk3xt1amhw/CqbyY+A9ljOMxc5IVr4ZeYMcT/7lFiZXZ7JQH4IBtbz1s9iBlIb2GqDmCVghDeg6IHBilHMb5OzttYqpbiRAHbNBi8ea6nM+a6PGf5PY/hQnmSJfzFGoNEchdJZmDbBgXa3B9s4IgjI+BSHMTQZ9mnWP6kk0ukE2XSKM5gKeNeAHpnYG+erwXqv9DYPFZZu6XGPE5LHbvguuw6Z/XDRgLg61kYNTZ5j6Hcrvjr1+/V4PoszplmktxO6aCCy/22kzjxXKgRkc+jUezRxUGB3RzLyVisKe8261rXfqWTwgwDB4XIwiTWP8FrMobCq2xxACm1xaDeBoZeKbcGPBmjTmxQKuWbmU5UTXTXNvIoqoc4EfIKJyHg04uzRTm46wxmNEM/5nDd723HapTdvXys80HVChIwn3nh8MgU4G766obW1tv6w3EnJ0M46EbMO2Kwd/Dw5uObHdO/ZqmV6DOInjaAU7IyRWxP3If4vJ6/WqtKw2tMCScTUN7V1eOliZ18+e0MDPFWc1b+ZwmNJE3KfiHQu9xkGGWC0n3+lJqahH3SoOYGBXfCxvXnx8JJ5MJcrgGn7QUUDyuX/eDJRV+l9NXcNqxQhbZ/JbIA0paqGVJs4JNyZC2fEXdCRo3vsj1pN8EghB39K+gMLnreA7ze41URHzYkP/NbZBNYnBwD1e4lviXB7ZmAbIdIHH90CtYEmS073vdwtKFeW/E/kXl8hHFiWbM+0VGUvMTTGDcDlrpOix/FlmdJuWo3NA3GE981i6AdrK4ahDSS/8qEU/TytJLx83U
  template:
    metadata:
      creationTimestamp: null
      name: radarr-helm-values
      namespace: default

