#cloud-config

fqdn: home.oho.io
manage_etc_hosts: true

locale: "en_US.UTF-8"
timezone: "Europe/Vienna"

chpasswd:
  list:
    - ubuntu:ubuntu

# Enable password authentication with the SSH daemon
ssh_pwauth: true

ssh_import_id:
  - gh:andreaseger

package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python3
  - python3-pip
  - gnupg2
  - fish

package_reboot_if_required: false

users:
  - default
  - name: ane
    primary-group: users
    shell: /usr/bin/fish
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh_import_id: gh:andreaseger
    lock_passwd: true
    ssh_pwauth: false

write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    permissions: "0644"
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            optional: true
            addresses:
              - 192.168.1.5/24
            gateway4: 192.168.1.1
            nameservers:
              addresses:
                - 1.1.1.1
                - 8.8.8.8
        wifis:
          wlan0:
            optional: true
            addresses:
              - 192.168.1.25/24
            gateway4: 192.168.1.1
            nameservers:
              addresses:
                - 1.1.1.1
                - 8.8.8.8
            access-points:
              ssid:
                password: ""

phone_home:
  url: http://192.168.1.122:2000
  post:
    - pub_key_ed25519
    - instance_id
    - hostname
  tries: 5

runcmd:
  - [sudo, netplan, apply]
  - [
      sudo,
      sed,
      -i,
      "s/PasswordAuthentication no/PasswordAuthentication yes/g",
      /etc/ssh/sshd_config,
    ]
  - [sudo, systemctl, restart, sshd]
