apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA435gJ9NXBc0KTP4YMSfQcVBQ9A4QN6UnwOmvKsB2Q1X/PfOoXd7+rJIrqIqXKNSqAuO6jwo1ZjmYx69KjwwcaBFk+OVHW740dGI9j7KghQXLaPaVNm58Gw1Ye1N1IQXyt3iXSowCcUpU6MP1X7bngGitNTV4p3f1PdnW4sRy1M+D1p5Xb0HBW/3FhZLiuM7y39krsLBsSWDCa4563bYNGQhwH8qrpuHU5pms5lc74u/8Pv/MtX78J0zKFozSzMJVUYn9A4k6cN5OkbtlcAn/fKgnqIgRJDzrZgvLpoH5bkaG5J57s9t9IUdlU+9LpxEaD2tXOVa3OCklzM7QXYiUj3CFuWc7wEjfAiLf3lsNdcVOSTlUZBsgWIqx+/OXQa+bnvf5Q2PNhF3vTG7f/RKq9c7bqB2OzYHrgYUUf0IeA2AMj2BwefdQqdEog27SGY7bkDxX2WI2CnoSzfBYYB2jxFlTxTmGvr4KSUJl4iiXJiea9GyUnkrWpf7Ctuz9S2TI2Or01nA/RgzleiZCHZa+Dt+Wd+7yftEf4DCs6Lzt4Nr9Kw3XvmDb3z9BufFlNygRbpX8I8ySYElb6LXVF+hPJudLljD0kiY+ebSiHAbxyjz4Ykn0Ff61H4wLAemYNx2/jZ5OTgcm4PUp/eB8uISPsasglPXqVX9E6KE0iTrbHTRx3+1NcmDekOotZgPcT2FsRbJw7UxyKUL0Pjit/Y0gVoBl/XDEQ+1tjgXVMBqHs3d8dJmXF5iT/W7BOEKW+i+7GF/ED3PEuUIQCPqrqeis1Zhbvi6A3kJMFmhB3GR+H+Zw91mxx0BEaBMoHCjKEtO2FasYsdrzKb2fBjewxmd1OIGob8ikMu3Kpx07ziNoc94kdk4tsa0SDAZtEKrnrUC0TUvSMSmdu4JlLdlD6xCKsz8gADGjouy7Hw/mnINlyYyjmymha2LIJs12AbInuBvXrtWyu39+2BYy7dMVbVi+xy6CUufyH9hua
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

