apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgB+3hcwbu0pzqnZ65M2sFQWdasTc8BnCM8/duPwdioEE3rgnNaX5E8S2WRM8sbrvxBDc3AfMN8FCfW/cruVD4jMMn38gwFfqzj1qF1ySkBEkJbOUErDzqrarWZNXynnjf+RarBiCdOeh5VMQBKGH5613FXdsN1lPK7UMS11JxkLIpQPVXZQy6+Ub4i/TRZ5UeuWfb7IpYdqbxKBhHvnXtDBY2kdOsnyCPQ5pygluyl5mSCFstMqlDCWXGUJJziOqVA8dn3jUdBunhbg0BNNV8y9A9eMpo4HHpnVC59lz1/dkP6pPQczcysCjne5l4TJxQCoNPltNWJu4bqVM4wFJXmwEYXEb62k1evgX4qeKYnOMZV+5JAEkgkjxWVsYQnMGWq3wLPKBdnexw50XM6eMhYIpxlHNEY6hQ9EO1MlHtSHPVhpis6zgRQOjfg3+cT6SgioDuOjZTdHpfSofyroxsm9QxQhOxruv934Yi7pbGWgPS4PRa9I5F9pAa9kAEgWjN7YODA10xHz9WFjAr9Fg+PgHpkb4duviXhLvOp94uFIty64dNzyTANy+273+vmk18bhFMDA4znju3+zaEhpj6Jy09Z9v7dlzsQilDw6GxCrZi6YzhmbPeONLOSpkfYlGvIW7XPAP2XsXtszTC2UUfMz54dSDL1fTOY6lnsSd0NVRS0U0zDrXTUdgpfWGcEtV8wWg0ifuCUynmMAkCXv5m06tdMhli5hZQ+1B0K1P3qRVum4MecfcqeJhAcFy678QFIZ5EMRQFN9+brXueuc4MbZy9MkYMBn4UckYtxJf4G1N1QWtXvPmTcbHyoGzxic/sUE1V5zHl4doupxJ2GkTPFAhmO/B/XFrK79VPCVABXBx293TvKL/qa/M7tGBmPOt2LRq//sjcACly+6rLbbtAXLhI1y7N1W3hnZGc3HSij2FqYilgARGahT9qR41IxcqW5vml7hu325rIBfSnBZPi9wZv6MjX2njm7mqbv4FlI3Khz7ayRoJAI0IU89g36Cd8yFr1S776jUts1L+3xNmBeHLH1/lCoGQG8lsw/W/1On97ryJQtCwhwLdXgys63ZFNPk23P1L0XwFTG0ow79bdi5WmglBtV7Cv/DbBPlohsJzRCBdhlh52LAjLfYYJYip6dfuxVva7VmQFqGmgXAOTX2PreqQTUMFp87FeCo6/gxXOQzPng0BhjUVs0AXmpAnCZ4mLl0KhgDSma3s8gQIW530DyNK66CrjPV0hpXVsKRTNWKMJI3dhYZgsvHwF1k9HTzFe4IPeAktMWTCMXqsQNDS5PLGyhkP55xWw0NGIUKI68eXm88spAZ9MnmXJ3B2zVaFb4XVORrJMAp5ZBePZC6TWQ=
  template:
    metadata:
      creationTimestamp: null
      name: plex-helm-values
      namespace: default

