apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgAwWjeQTkp2wmUc+eSx20hOFkh05J9YRMIdLhd94pshz53gBGhCOuFRJQdlErRS2NsKWt+/eU90i0rloICaufNy/nxAP+3P9sdCTscQDgKKP8nbPEwf1G//+038+fjauD1BOeevATVcm1BcjPTMPO4UsmjjDqyrQ6fg1hXYGhO5Ixo/LeexKuv4MuuY4p/09Dq0GuU/om8D3WfI4ltfNls5VFICWR1JJkTrdn2H0eGH9SeztNk7YlhHFTx/BMjut8oYlrJ/TICEiOhVGsK/6CupTIpW1hS0JTKCRyDIy4Tyipw3lrehkcQZnBvL3f0TarTJ2Zg8Df5XRFKc1h9/QF/iLjmTqjpDzltWm0f+uZBUtCjvIQ4TifnNHwuj25lvfqMQbXlnQD/Uu2QDUhTG/el0jw8DSqdxMUL3Jxn3Xf9id9JHilBYVKykXPMlJpOyHpzWHpODUiKwFEGtpR93JsDKtG9yW816yehBIh/7EYW1aV7Eiah/JnEoNoulErG1rHW8RKCn3hHbePddcPej9AAj03IOyjJWsDtJVX+9pUszb6SfaHtuYCsREK6nkTnoPVa0KZ0XGc7YK5VZD79QmPntBKWv2jfLNSi3OQwlNYfOlo6gye6npQVexEbZ89D1tcbefSQ9TFSHGyVPo4KpJsmEtkhL7nEF6LWkJsXNIC6F69/9E+V9Niu/6PMlGXSszcZcj76uSrHY38YpeNWScxvGL5Jxs3iGXy/b+Cula3O+1RDZeo0m94Et2Q/N7aywllMqSt39PK51WBSfacDWXdzCBFJI38Zf+P9Qd065K+aZUb8J3UxmOQ0u2lHEDJKDfKasyL8y5sbMrxX/J2y5qfH6YTXET74xSZqW67KI/0dBXcr8Kq4XvzA2bomguhxc0GKMRbID2Y7mvsujP2v/B9gL/KzE3LxqHNwErAd7v0Bwa/+oNjGRNMzYmewo4frgJKAO4t2Sjy283i/gOIr46zsLlPPj/Mb1L8KvvCbvabDKcyW+uMXNVVfpTPaYu0KxI0p28GxjubzLo5HqFIXXYRvwtKN0VCBg0gJlq0Hn1T09iaCs5TUaSawPn6bCY63pKVDeAzI3MKi4fyhfVn0f8KE7l6Wj6wgKOlImPZBqf1olTpaCmy3z3QF34F98h99eTEKBz2SQjoLi0SJYBJmvv33bVaAun13CAatNET3WvbnIaWCwEIfGLmpyocHnQ3ZPHycclV3TkoCyyND/u8ZijbmCHiMy8Qu7I/LOLfuXVTtnJda43CqJ5vkAPJf0If4Wh0egw7JOuCw59Jem3dupzB/alrRWmJ7vLk+SDOwJUSts7jp80FOSyX5tLn1/U4q1Ep+bAlz8Dlb37c5qpQXTyNnQB2LBviEX8CEsYA==
  template:
    metadata:
      creationTimestamp: null
      name: plex-helm-values
      namespace: default

