---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    replicas-max: "1"
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
spec:
  releaseName: plex
  helmVersion: v3
  rollback:
    enable: false
  forceUpgrade: false
  chart:
    repository: https://k8s-at-home.com/charts/
    name: plex
    version: 2.0.4
  values:
    image:
      repository: linuxserver/plex
      tag: version-1.20.2.3402-0fec14d92
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    timezone: Europe/Vienna
    allowedNetworks:
      - 192.168.1.0/24 # outside / host
      - 10.43.0.0/16   # k3s service cluster ips
      - 10.42.0.0/16   # k3s pod ips
    extraEnv:
      PUID: '"1000"'
      PGID: '"1000"'
    persistence:
      transcode:
        enabled: true
        storageClass: "local-path"
        size: 10Gi
      extraData:
        - claimName: local-media-pvc
          name: media
      config:
        enabled: true
        storageClass: "local-path"
        size: 5Gi
    resources:
      requests:
        cpu: 35m
        memory: 1500Mi
      limits:
        memory: 2Gi
  valueFileSecrets:
  - name: "plex-helm-values"